- sepolicy.mk
Building without sepolicy would be a very bad idea. This ensures build fails without it.
> Fix build of sepolicy on Marshmallow

- bluetooth.te
[ 6780.196291] type=1400 audit(1465692088.613:384): avc: denied { read write } for pid=12576 comm=hci_thread name=smd3 dev=tmpfs ino=9282 scontext=u:r:bluetooth:s0 tcontext=u:object_r:smd_device:s0 tclass=chr_file permissive=1
[ 6780.198091] type=1400 audit(1465692088.613:385): avc: denied { open } for pid=12576 comm=hci_thread path=/dev/smd3 dev=tmpfs ino=9282 scontext=u:r:bluetooth:s0 tcontext=u:object_r:smd_device:s0 tclass=chr_file permissive=1
[ 6780.205844] type=1400 audit(1465692088.623:386): avc: denied { ioctl } for pid=12576 comm=hci_thread path=/dev/smd3 dev=tmpfs ino=9282 ioctlcmd=540b scontext=u:r:bluetooth:s0 tcontext=u:object_r:smd_device:s0 tclass=chr_file permissive=1
> Sepolicy: avoid bluetooth denials

- platform_app.te
Allow NFC service to be found
avc:  denied  { find } for service=nfc scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:nfc_service:s0 tclass=service_manager
E NFC     : could not retrieve NFC service
Change-Id: I7cb653c80dd752a0965c5e36c6d9aad3149f95f1
> Fix platform_app denials

- file_contexts
- rild.te
06-15 01:06:33.979 I/rild    (  395): type=1400 audit(0.0:18): avc: denied { read } for name="name" dev="sysfs" ino=18168 scontext=u:r:rild:s0 tcontext=u:object_r:sysfs_pronto:s0 tclass=file permissive=1
06-15 01:06:33.979 I/rild    (  395): type=1400 audit(0.0:19): avc: denied { open } for path="/sys/devices/fb21b000.qcom,pronto/subsys2/name" dev="sysfs" ino=18168 scontext=u:r:rild:s0 tcontext=u:object_r:sysfs_pronto:s0 tclass=file permissive=1
> Sepolicy: avoid rild denials

- touchfusion.te
It is required for kernel@1.3.3
avc:  denied  { write } for  pid=452 comm="touch_fusion"
name="/" dev="tmpfs" ino=14122 scontext=u:r:touchfusion:s0
tcontext=u:object_r:device:s0 tclass=dir permissive=0
Change-Id: Id9741699e1da2ba1e63c1240458ab6e4bc68320b
> sony: sepolicy: Fix touchfusion denied

- file_contexts
- netmgrd.te
- sensors.te
- system_server.te
Add extra subsys, thermal, and pronto sysfs and grant access to them
> Fix some minor denials from honami

- mm-qcamerad.te
Rules are required for our Camera HAL so enabled for all types of build.
> Sepolicy: Let camera work on User builds

- lmkd.te
06-22 10:18:20.069 I/lmkd    (  324): type=1400 audit(0.0:7): avc: denied { search } for name=lowmemorykiller dev=sysfs ino=6510 scontext=u:r:lmkd:s0 tcontext=u:object_r:sysfs_lowmemorykiller:s0 tclass=dir permissive=1
> sepolicy: avoid lowmemorykiller denials

- file_contexts
it's FOTAKernel the partition used by sony bootloader for recovery
> sepolicy: fix recovery path for SELinux

- rild.te
These modifications enable sony users to make and receive calls. Without them it is impossible to end an
initiated call and receiving calls results in "SIM not found".
Already made a couple of calls with these modifications.
Change-Id: I5d4e70e3c516ded6c3df03f9ad4a20debb0fbd6c
> Add required rild sepolicy rules.

- file_contexts
It is causing multiple same definitions
> sepolicy: remove double selinux definitions

- logd.te
[   18.344641] type=1400 audit(25122845.559:4):
avc:  denied  { write } for  pid=455 comm="logd"
name="kmsg" dev="tmpfs" ino=13404 scontext=u:r:logd:s0
tcontext=u:object_r:device:s0 tclass=file permissive=0
Change-Id: I5834f0cc206504401e102704b1213a322cbd0521
> [m-mr1] sony: sepolicy: Address denial for logd

- zygote.te
[   7.3231] type=1400 audit(0.0:24):
avc: denied { open } for path="/dev/urandom"
dev="tmpfs" ino=250 scontext=u:r:zygote:s0
tcontext=u:object_r:device:s0 tclass=file permissive=0
Change-Id: I14cb36e3f15136233f01b30ede9e34ab199fc3f3
> [m-mr1] sony: sepolicy: Address denial for zygote

- touchfusion.te
[   15.725492] type=1400 audit(25036419.049:4): avc:  denied
{ create } for  pid=421 comm="touch_fusion" name="kmsg"
scontext=u:r:touchfusion:s0 tcontext=u:object_r:device:s0
Change-Id: Ic6d1edbb65f6f7ae2e58641a70a4c22d271f53e7
> [m-mr1] sony: sepolicy: Address touchfusion denial

- init.te
- kernel.te
- ueventd.te
this patch is required mainly for touchfusion.
avc:  denied  { write } for  pid=381 comm="touch_fusion"
name="/" dev="tmpfs" ino=297 scontext=u:r:kernel:s0
tcontext=u:object_r:tmpfs:s0 tclass=dir permissive=0
avc:  denied  { create } for  pid=371 comm="touch_fusion"
name="kmsg" scontext=u:r:kernel:s0
tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0
avc:  denied  { create } for  pid=382 comm="touch_fusion"
scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0
tclass=netlink_socket permissive=0
avc:  denied  { write } for  pid=378 comm="init" name="kmsg"
dev="tmpfs" ino=1032 scontext=u:r:init:s0
tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0
avc:  denied  { write } for  pid=378 comm="init" name="kmsg"
dev="tmpfs" ino=1032 scontext=u:r:init:s0
tcontext=u:object_r:tmpfs:s0 tclass=dir …
> [m-mr1] sony: sepolicy: Fix kernel, init and ueventd denials

- system_server.te
07-08 09:15:15.089: I/system_server(914): type=1400 audit(0.0:28): avc: denied { ioctl } for path=socket:[19688] dev=sockfs ino=19688 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1
07-08 09:15:15.089: I/system_server(914): type=1400 audit(0.0:29): avc: denied { ioctl } for path=socket:[19688] dev=sockfs ino=19688 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1
> sepolicy: avoid system_server denials

- debuggerd.te
[ 1546.909952] type=1400 audit(1468395418.843:745): avc: denied { read } for pid=400 comm=debuggerd name=kgsl-3d0 dev=tmpfs ino=8315 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
[ 1546.910464] type=1400 audit(1468395418.843:746): avc: denied { open } for pid=400 comm=debuggerd path=/dev/kgsl-3d0 dev=tmpfs ino=8315 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
[ 1546.910929] type=1400 audit(1468395418.843:747): avc: denied { getattr } for pid=400 comm=debuggerd path=/dev/kgsl-3d0 dev=tmpfs ino=8315 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
> sepolicy: avoid debuggerd denials

- kernel.te
One more touchfusion requirement.
<5>[   10.766743] type=1400 audit(25499759.889:4):
avc:  denied  { write } for  pid=368 comm="touch_fusion" name="/"
dev="tmpfs" ino=12435 scontext=u:r:kernel:s0
tcontext=u:object_r:device:s0 tclass=dir permissive=0
Change-Id: Iabf60483453b69d15ebbe238093051f12a29f7e7
> sony: sepolicy: Fix kernel denial

- perfprofd.te
09-01 11:55:49.877 550 550 W perfprofd: type=1400 audit(0.0:5):
avc: denied { open } for path="/dev/urandom" dev="tmpfs"
ino=307 scontext=u:r:perfprofd:s0 tcontext=u:object_r:device:s0
Change-Id: Iecfdeb481e09d6522e219c008be6d442b2c24f95
> sony: sepolicy: Address denial for perfprofd

- surfaceflinger.te
- system_server.te
This is required after latest aosp security update.
[   40.519101] type=1400 audit(1468462596.535:36):
avc: denied { ioctl } for pid=508 comm="Binder_2"
path="socket:[26176]" dev="sockfs" ino=26176
ioctlcmd=7704 scontext=u:r:surfaceflinger:s0
tcontext=u:r:surfaceflinger:s0
tclass=unix_stream_socket permissive=0
[   41.273510] type=1400 audit(1468462597.295:37):
avc: denied { ioctl } for pid=3271 comm="Binder_A"
path="socket:[27998]" dev="sockfs" ino=27998
ioctlcmd=7704 scontext=u:r:system_server:s0
tcontext=u:r:system_server:s0
tclass=unix_stream_socket permissive=0
Change-Id: I2fb8962cef42892c042b66dbccc7503995f49be2
> sony: sepolicy: Address denials for ioctl rules

- rild.te
[  583.100707] type=1400 audit(1468492785.389:5):
avc: denied { read } for pid=850 comm="rild"
name="system_health_monitor" dev="tmpfs"
ino=13452 scontext=u:r:rild:s0
tcontext=u:object_r:system_health_monitor_device:s0
tclass=chr_file permissive=0
Change-Id: Iceb7571370abdcf3be3533725e42270c594a6cea
> sony: sepolicy: Address denial for rild

- mm-qcamerad.te
[   15.299568] type=1400 audit(1469910130.019:6): avc: denied { read } for pid=1138 comm=CAM_MctServ name=fb0 dev=tmpfs ino=9887 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:graphics_device:s0 tclass=chr_file permissive=1
[   15.300698] type=1400 audit(1469910130.019:7): avc: denied { open } for pid=1138 comm=CAM_MctServ path=/dev/graphics/fb0 dev=tmpfs ino=9887 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:graphics_device:s0 tclass=chr_file permissive=1
[   15.300788] type=1400 audit(1469910130.019:8): avc: denied { ioctl } for pid=1138 comm=CAM_MctServ path=/dev/graphics/fb0 dev=tmpfs ino=9887 ioctlcmd=4600 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:graphics_device:s0 tclass=chr_file permissive=1
> sepolicy: avoid graphics denials for cam

- file.te
- file_contexts
- system_app.te
- timekeep.te
sony: sepolicy: Fix timekeep denials
Change-Id: I80b55ad8bb60a105dac9b7d348e47a694fcaa821
sony: sepolicy: Address denials for timekeep
avc: denied { fowner } for pid=444 comm="timekeep" capability=3
scontext=u:r:timekeep:s0 tcontext=u:r:timekeep:s0 tclass=capability permissive=0
avc: denied { fsetid } for capability=4 scontext=u:r:timekeep:s0
tcontext=u:r:timekeep:s0 tclass=capability permissive=0
Change-Id: Ie6c7af67a960b3c44b2678a17747fa18bbf1d2b8
> sony: sepolicy: Address denials for timekeep

- mm-qcamerad.te
08-20 19:06:24.976  2181  2181 I CAM_mct_freeze: type=1400 audit(0.0:56): avc: denied { read } for name=enable dev=debugfs ino=9635 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
> sepolicy: avoid cam denials

- init_shell.te
needed by: ee1a33bfc8f76c6aa22e6751cd5f61e6e378a969
also fixes some denials like:
08-18 16:32:45.186  4605  4605 I init    : type=1400 audit(0.0:12): avc: denied { execute_no_trans } for path="/system/bin/sh" dev="mmcblk0p23" ino=423 scontext=u:r:init:s0 tcontext=u:object_r:shell_exec:s0 tclass=file permissive=1
08-18 16:32:45.196  4606  4606 I getprop : type=1400 audit(0.0:13): avc: denied { write } for path="pipe:[33984]" dev="pipefs" ino=33984 scontext=u:r:toolbox:s0 tcontext=u:r:init:s0 tclass=fifo_file permissive=1
08-18 16:32:45.216  4606  4606 I getprop : type=1400 audit(0.0:14): avc: denied { getattr } for path="pipe:[33984]" dev="pipefs" ino=33984 scontext=u:r:toolbox:s0 tcontext=u:r:init:s0 tclass=fifo_file permissive=1
> sepolicy: add init_shell.te needed for bluetooth

- cameraserver.te
01-01 00:58:18.999 19097 19097 I cameraserver: type=1400 audit(0.0:517): avc: denied { read write } for name=kgsl-3d0 dev=tmpfs ino=612 scontext=u:r:cameraserver:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
01-01 00:58:18.999 19097 19097 I cameraserver: type=1400 audit(0.0:518): avc: denied { open } for path=/dev/kgsl-3d0 dev=tmpfs ino=612 scontext=u:r:cameraserver:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
01-01 00:58:18.999 19097 19097 I cameraserver: type=1400 audit(0.0:519): avc: denied { ioctl } for path=/dev/kgsl-3d0 dev=tmpfs ino=612 ioctlcmd=902 scontext=u:r:cameraserver:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
> sepolicy: avoid selinux denials

- untrusted_app.te
08-27 17:45:06.774  3966  3966 I Executor-4: type=1400 audit(0.0:5): avc: denied { open } for path=/dev/__properties__/u:object_r:camera_prop:s0 dev=tmpfs ino=10858 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=1
08-27 17:45:06.774  3966  3966 I Executor-4: type=1400 audit(0.0:6): avc: denied { getattr } for path=/dev/__properties__/u:object_r:camera_prop:s0 dev=tmpfs ino=10858 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=1
> sepolicy: avoid Google Cam denials

- file.te
- file_contexts
- pad_controller.te
- property.te
- property_contexts
Required for proximity driver.
> sony: sepolicy: Address pad_controller denials

- radio.te
09-09 14:35:17.827  2503  2503 I m.android.phone: type=1400 audit(0.0:10):
avc: denied { getattr } for path="/data/user_de/0/com.android.settings"
dev="mmcblk0p43" ino=457945 scontext=u:r:radio:s0
tcontext=u:object_r:system_app_data_file:s0 tclass=dir permissive=0
Change-Id: I40380fdeb1cd7646ec75d348ad0a575dd176d0b9
> sony: sepolicy: Address radio denied

- recovery.te
- uncrypt.te
Android Nougat changed how it communicates with the recovery
partition. Until now the recovery commands had been written
to the /cache partition, but this has changed. Now recovery
writes to the /misc partition.
Fortunately for kitakami devices and beyond we actually have
an empty and unused /misc partition we can use. For older
devices we'll need to be creative.
> Allow recovery to use the misc partition and read the syslog

- audioserver.te
[   16.633004] type=1400 audit(1474049901.839:3): avc: denied { read }
for pid=460 comm="audioserver" name="class" dev="sysfs" ino=10
scontext=u:r:audioserver:s0 tcontext=u:object_r:sysfs:s0
tclass=dir permissive=0
[   16.633120] type=1400 audit(1474049901.839:4): avc: denied { open }
for pid=460 comm="audioserver" path="/sys/class" dev="sysfs"
ino=10 scontext=u:r:audioserver:s0 tcontext=u:object_r:sysfs:s0
tclass=dir permissive=0
[   16.635582] type=1400 audit(1474049901.839:5): avc: denied { read }
for pid=460 comm="audioserver" name="type" dev="sysfs" ino=23402
scontext=u:r:audioserver:s0 tcontext=u:object_r:sysfs:s0
[   16.639400] type=1400 audit(1474049901.839:6): avc: denied { read open }
for pid=460 comm="audioserver" …
> [master] sony: sepolicy: Address audioserver denials

- netmgrd.te
[   19.874101] type=1400 audit(1474049905.079:9): avc: denied { write }
for pid=1034 comm="sh" name="rps_cpus" dev="sysfs"
ino=21845 scontext=u:r:netmgrd:s0 tcontext=u:object_r:sysfs:s0
> [master] sony: sepolicy: Address netmgrd denials

- kernel.te
[   16.658265] type=1400 audit(1474049901.859:8): avc: denied { create }
for pid=51 comm="kworker/u12:2" scontext=u:r:kernel:s0
tcontext=u:r:kernel:s0 tclass=socket permissive=0
> [master] sony: sepolicy: Address kernel denied

- file_contexts
- tad.te
rework tad configuration
use trim_area_partition_device instead of tad_block_device
and set RW permissions to its block devices.
Fix:
tad : Trim Area daemon starting.
tad : Using trim area info (0,16) from arguments.
tad : Failed to open /dev/block/bootdevice/by-name/TA (Permission denied)
tad : Failed to configure TA library.
Address tad denials for common block devices operation (search):
tad_static: type=1400 audit(0.0:4):
avc: denied { search } for name="block" dev="tmpfs" ino=14444
scontext=u:r:tad:s0 tcontext=u:object_r:block_device:s0
tclass=dir permissive=0
Change-Id: I6775680d815202a958a1fff9b1e4b237f50b93e5
> [master] sony: sepolicy: Address tad denials

- gatekeeperd.te
gatekeeperd: type=1400 audit(0.0:6): avc: denied { search }
for name="/" dev="mmcblk0p3" ino=1 scontext=u:r:gatekeeperd:s0
tcontext=u:object_r:firmware_file:s0 tclass=dir permissive=0
Change-Id: Idd64a56049858af4e88f874e86acf10753b8728e
> [master] sony: sepolicy: Address gatekeeperd denials

- mm-qcamerad.te
CAM_MctServ: type=1400 audit(0.0:8): avc: denied { search }
for name="graphics" dev="tmpfs" ino=14787 scontext=u:r:mm-qcamerad:s0
tcontext=u:object_r:graphics_device:s0 tclass=dir permissive=0
Change-Id: I9af7d5890a9f5cc0fb750fd2f25182da0701aebb
> [master] sony: sepolicy: Address mm-qcamerad denials

- file.te
- file_contexts
- pad_controller.te
This patch uses another approach to hadling pad_controller sysfs files.
> [master] sony: sepolicy: Optimize pad_controller dependencies

- file.te
- file_contexts
- pad_controller.te
- property.te
- property_contexts
Required for proximity driver.
Change-Id: I8508061cf3394d14c2a631ee77bb16eb73085148
> [m-mr1][tiny version] sony: sepolicy: Address pad_controller denials

- file_contexts
8974 uses /apps_log as /misc 8994 uses /misc as /misc 8952/56 uses /apps_log as /misc
Following Nexus Angler as base
avoid denials like:
picked from honami - rhine
[   51.159615] type=1400 audit(1474811177.738:5): avc: granted { write } for pid=4156 comm="uncrypt" name="mmcblk0p22" dev="tmpfs" ino=4884 scontext=u:r:uncrypt:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
[   51.180788] type=1400 audit(1474811177.738:6): avc: granted { write open } for pid=4156 comm="uncrypt" path="/dev/block/mmcblk0p22" dev="tmpfs" ino=4884 scontext=u:r:uncrypt:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file
> sepolicy: add correct selinux definitions for /misc partition

- property.te
- property_contexts
- system_app.te
this allows using ES alongside with the custom implementation some
custom roms use be appending an "es" to the respective code.
> selinux: Rename adb over network com property

- addrsetup.te
- debuggerd.te
- fsck.te
- init.te
- lmkd.te
- logd.te
- ueventd.te
- vold.te
Kernel 3.18 needs permissions mostly for /dev/urandom
and then, e2fsck was lacking permissions to open
block devices, resulting in unability to run fsck
on filesystems at boot.
Also, fix init permissions for persist mount.
> [3.10/3.18 N] Add permissions for urandom, e2fsck, init

- init.te
09-21 23:20:05.401   539   539 I brcm-uim-sysfs: type=1400 audit(0.0:196): avc: denied { write } for name=ttyHS0 dev=tmpfs ino=11777 scontext=u:r:init:s0 tcontext=u:object_r:hci_attach_dev:s0 tclass=chr_file permissive=1
09-21 23:20:05.411   539   539 I brcm-uim-sysfs: type=1400 audit(0.0:197): avc: denied { ioctl } for path=/dev/ttyHS0 dev=tmpfs ino=11777 ioctlcmd=540b scontext=u:r:init:s0 tcontext=u:object_r:hci_attach_dev:s0 tclass=chr_file permissive=1
> sepolicy: avoid BCM FM denials

- addrsetup.te
[   14.526114] type=1400 audit(10022.679:3): avc: denied { chown } for pid=376 comm=macaddrsetup capability=0 scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=capability permissive=1
[   14.526549] type=1400 audit(10022.679:4): avc: denied { fowner } for pid=376 comm=macaddrsetup capability=3 scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=capability permissive=1
[   14.526623] type=1400 audit(10022.679:5): avc: denied { fsetid } for pid=376 comm=macaddrsetup capability=4 scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=capability permissive=1
> sepolicy: avoid macaddrsetup denials

- file_contexts
- vold.te
avoid
01-01 02:17:25.970   426   426 I e2fsck  : type=1400 audit(0.0:3): avc: denied { getattr } for path=/dev/block/zram0 dev=tmpfs ino=4812 scontext=u:r:vold:s0 tcontext=u:object_r:swap_block_device:s0 tclass=blk_file permissive=1
> sepolicy: SELinux for zram0

- addrsetup.te
- bluetooth.te
- file.te
- file_contexts
Write the bluetooth macaddr to a place that is natively readable
by bluetooth services, instead of creating new locations which
requires excessive permissions.
> macaddr: remove dangerous sepolicy permissions

- file_contexts
FAILED: /run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/target/product/amami/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp 
/bin/bash -c "(/run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/host/linux-x86/bin/checkfc -e /run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/target/product/amami/obj/ETC/sepolicy_intermediates/sepolicy /run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/target/product/amami/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp ) && (/run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/host/linux-x86/bin/fc_sort /run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/target/product/amami/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp /run/media/sc/4T3/ROMs/AICP-n7.0_repo/out/target/product/amami/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.sorted.tmp …
> Remove duplicate specification of /sys/devices/platform/bcmdhd_wlan/macaddr

- file_contexts
the new kernel uses soc instead of soc.0 sysfs path
> sepolicy: switch to 3.18 kernel

- device.te
- uncrypt.te
misc_partition is deprecated in Nougat
also they are already defined by AOSP
https://android.googlesource.com/platform/system/sepolicy/+/android-7.0.0_r14/device.te#99
https://android.googlesource.com/platform/system/sepolicy/+/android-7.0.0_r14/uncrypt.te#28
> sepolicy: Use new AOSP label for misc

- per_mgr.te
[   13.994953] type=1400 audit(17091591.159:3): avc: denied { read }
for pid=418 comm="pm-service" name="name" dev="sysfs" ino=20529
scontext=u:r:per_mgr:s0 tcontext=u:object_r:sysfs_pronto:s0
[   13.998772] type=1400 audit(17091591.159:4): avc: denied { open }
for pid=418 comm="pm-service"
path="/sys/devices/soc.0/a21b000.qcom,pronto/subsys2/name"
dev="sysfs" ino=20529 scontext=u:r:per_mgr:s0
tcontext=u:object_r:sysfs_pronto:s0 tclass=file permissive=0
[   14.981932] type=1400 audit(1478475975.000:5): avc: denied { read }
for pid=482 comm="pm-proxy" name="name" dev="sysfs" ino=20529
scontext=u:r:per_mgr:s0 tcontext=u:object_r:sysfs_pronto:s0
[   14.982325] type=1400 audit(1478475975.000:6): avc: denied { open }
for pid=482 comm="pm-proxy" …
> sony: sepolicy: Address per_mgr denials

- bluetooth.te
01-01 20:25:52.359  2193  2193 I droid.bluetooth: type=1400 audit(0.0:3): avc: denied { getattr } for path=/storage/emulated dev=tmpfs ino=21678 scontext=u:r:bluetooth:s0 tcontext=u:object_r:storage_stub_file:s0 tclass=dir permissive=1
> sepolicy: avoid bt denial

- bluetooth.te
- file.te
- file_contexts
- init.te
- platform_app.te
- ueventd.te
- uim.te
The service "uim /system/bin/brcm-uim-sysfs"
should be labeled as seclabel u:r:uim:s0
Change-Id: I5e943e3eef6f344040dd1ba975442a456fdbbf35
> sony: sepolicy: Address UIM (BT FM) denials

- audioserver.te
- bootanim.te
- cameraserver.te
- init.te
- mediacodec.te
- mediadrmserver.te
- uim.te
01-09 06:49:29.579     1     1 I init    : type=1400 audit(0.0:3): avc: denied { write } for name=tracing_on dev=debugfs ino=6843 scontext=u:r:init:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
01-09 06:49:30.809   520   520 I audioserver: type=1400 audit(0.0:4): avc: denied { getattr } for path=/vendor dev=rootfs ino=10902 scontext=u:r:audioserver:s0 tcontext=u:object_r:rootfs:s0 tclass=lnk_file permissive=1
01-09 06:49:30.809   522   522 I cameraserver: type=1400 audit(0.0:5): avc: denied { getattr } for path=/vendor dev=rootfs ino=10902 scontext=u:r:cameraserver:s0 tcontext=u:object_r:rootfs:s0 tclass=lnk_file permissive=1
01-09 06:49:30.829   526   526 I mediacodec: type=1400 audit(0.0:6): avc: denied { getattr } for path=/vendor dev=rootfs ino=10902 …
> sepolicy: avoid 7.1.x denials

- file_contexts
it is a 3.18 kernel requirement.
Change-Id: If2f8e131ddc7a7218949a899872b9b170cc46fec
> [master] sony: sepolicy: Update brcm bt fm sysfs path

- file_contexts
Required at 3.18 kernel
Change-Id: I2dd01be93a19ac3df190b062f4e4a4c8f9f0f3d3
> sony: sepolicy: Address macaddrsetup denials

- system_app.te
12-13 09:57:13.190  3924  3924 I MemoryMeasureme: type=1400 audit(0.0:3): avc: denied { read open } for path=/data/media/0 dev=mmcblk0p42 ino=670435 scontext=u:r:system_app:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
12-13 09:57:13.190  3924  3924 I MemoryMeasureme: type=1400 audit(0.0:4): avc: denied { search } for name=0 dev=mmcblk0p42 ino=670435 scontext=u:r:system_app:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
> sepolicy: avoid memory explorer denials

- mediaserver.te
- mm-qcamerad.te
12-22 12:47:08.587  9508  9508 I mm-qcamera-daem: type=1400 audit(0.0:28): avc: denied { use } for path=anon_inode:dmabuf dev=anon_inodefs ino=12273 scontext=u:r:mm-qcamerad:s0 tcontext=u:r:mediaserver:s0 tclass=fd permissive=1
12-22 12:47:28.107  2274  2274 I Binder:1113_2: type=1400 audit(0.0:29): avc: denied { sendto } for path=/data/misc/camera/cam_socket2 scontext=u:r:mediaserver:s0 tcontext=u:r:mm-qcamerad:s0 tclass=unix_dgram_socket permissive=1
merge this after
https://github.com/sonyxperiadev/device-sony-rhine/pull/270
https://github.com/sonyxperiadev/device-sony-shinano/pull/332
> [HAL1]sepolicy: avoid cam denials

- mediaserver.te
- mm-qcamerad.te
12-30 20:52:55.495   390   390 W mediaserver: type=1400 audit(0.0:2910): avc: denied { search } for name=camera dev=mmcblk0p25 ino=431675 scontext=u:r:mediaserver:s0 tcontext=u:object_r:camera_data_file:s0 tclass=dir permissive=0
12-30 22:21:58.533  1041  1041 W CAM_MctServ: type=1400 audit(0.0:4): avc: denied { search } for name="graphics" dev="tmpfs" ino=6069 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:graphics_device:s0 tclass=dir permissive=0
12-31 10:03:57.831 11212 11212 W CAM_MctServ: type=1400 audit(0.0:48): avc: denied { create } for name="fdAlbum" scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:camera_data_file:s0 tclass=file permissive=0
permissive mode too
01-04 17:11:10.743  7748  7748 I CAM_MctServ: type=1400 audit(0.0:7): avc: denied { create } for name="fdAlbum" …
> sepolicy: avoid cam denials in enforcing

- vold.te
01-04 21:15:33.997   455   455 I vold    : type=1400 audit(0.0:7): avc: denied { read } for name=2D3B-1CF0 dev=tmpfs ino=82146 scontext=u:r:vold:s0 tcontext=u:object_r:storage_stub_file:s0 tclass=dir permissive=1
01-04 21:15:33.997   455   455 I vold    : type=1400 audit(0.0:8): avc: denied { open } for path=/storage/2D3B-1CF0 dev=tmpfs ino=82146 scontext=u:r:vold:s0 tcontext=u:object_r:storage_stub_file:s0 tclass=dir permissive=1
01-04 21:15:33.997   455   455 I vold    : type=1400 audit(0.0:9): avc: denied { write } for name=2D3B-1CF0 dev=tmpfs ino=82146 scontext=u:r:vold:s0 tcontext=u:object_r:storage_stub_file:s0 tclass=dir permissive=1
01-04 21:15:33.997   455   455 I vold    : type=1400 audit(0.0:10): avc: denied { add_name } for name=Android scontext=u:r:vold:s0 …
> sepolicy: avoid vold denials

- fingerprintd.te
- init.te
- netmgrd.te
[   21.956000] type=1400 audit(8045725.589:3): avc: denied { write } for pid=1 comm=init name=interactive dev=sysfs ino=37526 scontext=u:r:init:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=1
58] init: avc:  denied  { set } for property=persist.net.doxlat pid=477 uid=1001 gid=3003 scontext=u:r:netmgrd:s0 tcontext=u:object_r:default_prop:s0 tclass=property_service permissive=1
[   38.862318] type=1400 audit(1483657932.759:4): avc: denied { write } for pid=499 comm=fingerprintd name=spi_prepare dev=sysfs ino=28908 scontext=u:r:fingerprintd:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
> sepolicy: avoid 3.18 denials

- file_contexts
- isolated_app.te
chrome uses GPU and GPU is handled by thermal...
01-06 15:05:39.297  7460  7460 I CrGpuMain: type=1400 audit(0.0:8): avc: denied { read } for name=reset_count dev=sysfs ino=10880 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
01-06 15:05:39.297  7460  7460 I CrGpuMain: type=1400 audit(0.0:9): avc: denied { open } for path=/sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/reset_count dev=sysfs ino=10880 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
01-06 15:05:39.297  7460  7460 I CrGpuMain: type=1400 audit(0.0:10): avc: denied { getattr } for path=/sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/reset_count dev=sysfs ino=10880 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 …
> sepolicy: avoid chrome denials

- file_contexts
- untrusted_app.te
Allow ContacsProvider access to Zram block
01-09 10:55:41.409  3457  3457 I ContactsProvide: type=1400 audit(0.0:3): avc: denied { search } for name=zram0 dev=sysfs ino=12651 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_zram:s0 tclass=dir permissive=1
01-09 10:55:41.409  3457  3457 I ContactsProvide: type=1400 audit(0.0:4): avc: denied { read } for name=mem_used_total dev=sysfs ino=12718 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_zram:s0 tclass=file permissive=1
01-09 10:55:41.419  3457  3457 I ContactsProvide: type=1400 audit(0.0:5): avc: denied { open } for path=/sys/devices/virtual/block/zram0/mem_used_total dev=sysfs ino=12718 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_zram:s0 tclass=file permissive=1
01-09 …
> sepolicy: avoid Zram denials

- system_app.te
01-10 23:53:55.640 11242 11242 I MemoryMeasureme: type=1400 audit(0.0:21): avc: denied { read open } for path=/data/media/0 dev=mmcblk0p25 ino=757395 scontext=u:r:system_app:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
01-10 23:53:55.650 11242 11242 I MemoryMeasureme: type=1400 audit(0.0:22): avc: denied { search } for name=0 dev=mmcblk0p25 ino=757395 scontext=u:r:system_app:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
> sepolicy: avoid settings denials

- adbd.te
- isolated_app.te
01-01 00:09:15.189  4192  4192 W /sbin/adbd: type=1400 audit(0.0:4): avc: denied { search } for comm=73657276696365203537 name=security dev=mmcblk0p25 ino=746305 scontext=u:r:adbd:s0 tcontext=u:object_r:security_file:s0 tclass=dir permissive=0
01-24 00:31:29.770  8081  8081 W dboxed_process0: type=1400 audit(0.0:33): avc: denied { search } for name=tmp dev=mmcblk0p25 ino=267698 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0
> sepolicy: avoid more denials

- keystore.te
02-01 01:25:04.249   458   458 I keystore: type=1400 audit(0.0:3): avc: denied { read } for name="u:object_r:tee_prop:s0" dev="tmpfs" ino=11687 scontext=u:r:keystore:s0 tcontext=u:object_r:tee_prop:s0 tclass=file permissive=1
02-01 01:25:04.249   458   458 I keystore: type=1400 audit(0.0:4): avc: denied { open } for path="/dev/__properties__/u:object_r:tee_prop:s0" dev="tmpfs" ino=11687 scontext=u:r:keystore:s0 tcontext=u:object_r:tee_prop:s0 tclass=file permissive=1
02-01 01:25:04.249   458   458 I keystore: type=1400 audit(0.0:5): avc: denied { getattr } for path="/dev/__properties__/u:object_r:tee_prop:s0" dev="tmpfs" ino=11687 scontext=u:r:keystore:s0 tcontext=u:object_r:tee_prop:s0 tclass=file permissive=1
> sepolicy: avoid keystore denials

- drmserver.te
01-31 21:59:32.788  4339  4339 I Binder:475_2: type=1400 audit(0.0:13): avc: denied { read } for path=/data/system_de/0/ringtones/alarm_alert_cache dev=mmcblk0p51 ino=114246 scontext=u:r:drmserver:s0 tcontext=u:object_r:ringtone_file:s0 tclass=file permissive=1
> sepolicy: avoid denials

- addrsetup.te
06-30 15:32:14.307   437   437 I macaddrsetup: type=1400 audit(0.0:3): avc: denied { write } for name=macaddr dev=sysfs ino=22442 scontext=u:r:addrsetup:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
06-30 15:32:43.777  3152  3152 I macaddrsetup: type=1400 audit(0.0:4): avc: denied { write } for name=macaddr dev=sysfs ino=22442 scontext=u:r:addrsetup:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
> sepolicy: avoid mac denials

- file_contexts
correct value is 115 not 114 see https://github.com/sonyxperiadev/device-sony-loire/commit/3faf836a41e90d69edbdb9b1a70eba2d628831b8
> sepolicy: update mac address path for loire

- rild.te
12-01 16:37:34.378   470   470 E SELinux : avc:  denied  { find } for service=media.audio_flinger pid=531 uid=1001 scontext=u:r:rild:s0 tcontext=u:object_r:audioserver_service:s0 tclass=service_manager permissive=1
> sepolicy: avoid rild denial

- file_contexts
needed after recent DT changes in kernel for loire
> sepolicy: loire: fix macaddr path

- device.te
- file_contexts
- isolated_app.te
- mm-qcamerad.te
- system_server.te
01-01 20:50:14.876   867   867 W CAM_MctServ: type=1400 audit(0.0:4): avc: denied { search } for name=graphics dev=tmpfs ino=6950 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:graphics_device:s0 tclass=dir permissive=0
02-14 09:51:13.495  7924  7924 W CAM_MctServ: type=1400 audit(0.0:12): avc: denied { create } for name="fdAlbum" scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:camera_data_file:s0 tclass=file permissive=0
02-14 12:18:53.666   948   948 W system_server: type=1400 audit(0.0:4): avc: denied { search } for name=/ dev=mmcblk0p36 ino=2 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=dir permissive=0
02-14 12:19:08.906  2113  2113 W ConnectivitySer: type=1400 audit(0.0:9): avc: denied { read } for name=u:object_r:xlat_prop:s0 dev=tmpfs ino=11349 …
> sony-common: loire: avoid enforcing selinux denials

- mediaserver.te
- mm-qcamerad.te
enforcing mode on 8952
02-16 13:27:57.417  2870  2870 W mediaserver: type=1400 audit(0.0:1950): avc: denied { search } for name=camera dev=mmcblk0p51 ino=171403 scontext=u:r:mediaserver:s0 tcontext=u:object_r:camera_data_file:s0 tclass=dir permissive=0
02-16 13:51:46.700   500   500 W mediaserver: type=1400 audit(0.0:33): avc: denied { sendto } for path="/data/misc/camera/cam_socket1" scontext=u:r:mediaserver:s0 tcontext=u:r:mm-qcamerad:s0 tclass=unix_dgram_socket permissive=0
02-16 13:51:46.933   500   500 W mediaserver: type=1400 audit(0.0:34): avc: denied { sendto } for path="/data/misc/camera/cam_socket2" scontext=u:r:mediaserver:s0 tcontext=u:r:mm-qcamerad:s0 tclass=unix_dgram_socket permissive=0
02-16 13:59:09.470   495   495 W mm-qcamera-daem: type=1400 audit(0.0:7): avc: denied { …
> sepolicy: avoid camera denials

- device.te
- file_contexts
- isolated_app.te
- mm-qcamerad.te
- system_server.te
01-01 20:50:14.876   867   867 W CAM_MctServ: type=1400 audit(0.0:4): avc: denied { search } for name=graphics dev=tmpfs ino=6950 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:graphics_device:s0 tclass=dir permissive=0
02-14 09:51:13.495  7924  7924 W CAM_MctServ: type=1400 audit(0.0:12): avc: denied { create } for name="fdAlbum" scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:camera_data_file:s0 tclass=file permissive=0
02-14 12:18:53.666   948   948 W system_server: type=1400 audit(0.0:4): avc: denied { search } for name=/ dev=mmcblk0p36 ino=2 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=dir permissive=0
02-14 12:19:08.906  2113  2113 W ConnectivitySer: type=1400 audit(0.0:9): avc: denied { read } for name=u:object_r:xlat_prop:s0 dev=tmpfs ino=11349 …
> sony-common: avoid enforcing selinux denials

- system_app.te
- vold.te
system_app.te: settings app needs access to fuse to get usage stats
vold.te: selinux reports vold denies when mounting sdcard
the denies solved are:
[ 1182.165576] type=1400 audit(1488221389.184:215): avc: denied {
getattr } for pid=7174 comm="ndroid.settings" name="/" dev="mmcblk1p1"
ino=1 scontext=u:r:system_app:s0 tcontext=u:object_r:fuse_device:s0
tclass=filesystem permissive=0
[ 1953.618601] type=1400 audit(1488222160.634:552): avc: denied { write
} for pid=424 comm="vold" name="data" dev="mmcblk1p1" ino=3
scontext=u:r:vold:s0 tcontext=u:object_r:fuse_device:s0 tclass=dir
permissive=0
[ 4819.557559] type=1400 audit(1488225299.224:744): avc: denied { read
open } for pid=424 comm="vold" path="/mnt/media_rw/24B5-1131"
dev="mmcblk1p1" ino=1 scontext=u:r:vold:s0 …
> [n-mr1] sepolicy: add vold and sdcard related rules

- system_app.te
- vold.te
system_app.te: settings app needs access to fuse to get usage stats
vold.te: selinux reports vold denies when mounting sdcard
the denies solved are:
[ 1182.165576] type=1400 audit(1488221389.184:215): avc: denied {
getattr } for pid=7174 comm="ndroid.settings" name="/" dev="mmcblk1p1"
ino=1 scontext=u:r:system_app:s0 tcontext=u:object_r:fuse_device:s0
tclass=filesystem permissive=0
[ 1953.618601] type=1400 audit(1488222160.634:552): avc: denied { write
} for pid=424 comm="vold" name="data" dev="mmcblk1p1" ino=3
scontext=u:r:vold:s0 tcontext=u:object_r:fuse_device:s0 tclass=dir
permissive=0
[ 4819.557559] type=1400 audit(1488225299.224:744): avc: denied { read
open } for pid=424 comm="vold" path="/mnt/media_rw/24B5-1131"
dev="mmcblk1p1" ino=1 scontext=u:r:vold:s0 …
> [n-mr0] sepolicy: add vold and sdcard related rules

- kernel.te
- uncrypt.te
avc: denied { mknod } for capability=27
scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0
avc: denied { create } for name="hwC0D49" scontext=u:r:kernel:s0
tcontext=u:object_r:device:s0 tclass=chr_file permissive=0
avc: denied { write } for name="kmsg" dev="tmpfs" ino=6922
scontext=u:r:uncrypt:s0 tcontext=u:object_r:kmsg_device:s0
tclass=chr_file permissive=0
Change-Id: I5312991bef7d031a9fa5a9afce6904ddacefcfcc
> sony: sepolicy: Address kernel and uncrypt denials

- kernel.te
avc: denied { getattr } for path="/input/event8"
dev="devtmpfs" ino=103800 scontext=u:r:kernel:s0
tcontext=u:object_r:device:s0 tclass=chr_file permissive=0
Change-Id: Ieec869f191238b4956c29db68f28560c779ebf21
> sony: sepolicy: Address kernel denied

- file_contexts
This reverts commit be13c277cbec3aa5ce8cca1e0416e95772ef8dc5.
> Revert "sepolicy: loire: fix macaddr path"

- bluetooth.te
03-13 22:00:22.049  5841  5841 I Binder_2: type=1400 audit(0.0:13): avc: denied { ioctl } for path=socket:[33284] dev=sockfs ino=33284 ioctlcmd=7704 scontext=u:r:bluetooth:s0 tcontext=u:r:bluetooth:s0 tclass=unix_stream_socket permissive=1
> sepolicy: avoid bt denials

- mediaserver.te
avc: denied { add } for service=media.camera pid=529 uid=1013 scontext=u:r:mediaserver:s0 tcontext=u:object_r:cameraserver_service:s0 tclass=service_manager permissive= 0
avc: denied { find } for service=media.camera.proxy pid=532 uid=1013 scontext=u:r:mediaserver:s0 tcontext=u:object_r:cameraproxy_service:s0 tclass=service_manager permissive=0
> sepolicy: avoid mediaserver denials

- init.te
- kernel.te
- touchfusion.te
- ueventd.te
It is required for karin's touchscreen (touch_fusion).
Change-Id: I6295c7b1e02024fa0ffb2d72cd70e768cd895678
> [n-mr1] sony: sepolicy: Fix touch_fusion denials

- priv_app.te
- rild.te
- untrusted_app.te
avc: denied { call } for pid=871 comm="rild"
scontext=u:r:rild:s0 tcontext=u:r:audioserver:s0 tclass=binder permissive=0
avc: denied { read } for pid=3232
comm="com.cpuid.cpu_z" name="temp1_input" dev="sysfs" ino=36313
scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0
avc: denied { setattr } for pid=2308 comm="MediaScannerSer" name="files"
dev="mmcblk1p1" ino=180 scontext=u:r:priv_app:s0:c512,c768
tcontext=u:object_r:vfat:s0 tclass=dir permissive=0
avc: denied { create } for pid=2292 comm=".apps.translate"
name="tmp_dir_should_be_removed" scontext=u:r:untrusted_app:s0:c512,c768
tcontext=u:object_r:vfat:s0:c512,c768 tclass=dir permissive=0
avc: denied { rmdir } for pid=2297 comm=".apps.translate"
name="tmp_dir_should_be_removed" dev="mmcblk1p1" …
> [master] Address rild, priv_app and untrusted_app denials.

- bootstat.te
bootstat is looking for vendor partition or vendor symlink
04-20 11:36:45.569  3021  3021 W bootstat: type=1400 audit(0.0:4): avc: denied { getattr } for path=/vendor dev=rootfs ino=6256 scontext=u:r:bootstat:s0 tcontext=u:object_r:rootfs:s0 tclass=lnk_file permissive=0
> sepolicy: add bootstat selinux

- kernel.te
- keystore.te
05-09 09:54:15.579    32    32 W kdevtmpfs: type=1400 audit(0.0:4): avc: denied { mknod } for capability=27 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0
05-09 10:36:34.149   489   489 W keystore: type=1400 audit(0.0:4): avc: denied { search } for name="/" dev="mmcblk0p3" ino=1 scontext=u:r:keystore:s0 tcontext=u:object_r:firmware_file:s0 tclass=dir permissive=0
> sepolicy: avoid 3.10 denials

- system_app.te
06-06 23:18:02.550  7457  7457 W com.android.settings: type=1400 audit(0.0:7): avc: denied { call } for comm=4173796E635461736B202339 scontext=u:r:system_app:s0 tcontext=u:r:fingerprintd:s0 tclass=binder permissive=0
> sepolicy: fix settings denial

- priv_app.te
06-13 23:23:24.587 20157 20157 W MtpServer: type=1400 audit(0.0:82): avc: denied { rename } for name=4E756F76612063617274656C6C61 dev=mmcblk1p1 ino=270 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vfat:s0 tclass=dir permissive=0
> sepolicy: fix mtp denial

- mm-qcamerad.te
06-19 21:15:49.791  6625  6625 W CAM_mct_freeze: type=1400 audit(0.0:10): avc: denied { read } for name=clk dev=debugfs ino=1112 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:debugfs:s0 tclass=dir permissive=0
> sepolicy: fix cam denial

- cnss-daemon.te
The daemon requires reading the same netlink sockets that it creates.
> [SEPOLICY] cnss-daemon: Allow netlink_socket read

- file_contexts
We have moved these context declarations to platform-specific
repositories.
> [SEPOLICY] Remove dev block nodes from common file_contexts

- radio.te
06-27 09:39:45.441  1958  1958 W Binder:1626_4: type=1400 audit(0.0:21): avc: denied { search } for name=data dev=mmcblk0p54 ino=791534 scontext=u:r:radio:s0 tcontext=u:object_r:media_rw_data_file:s0:c512,c768 tclass=dir permissive=0
06-27 09:39:45.441  1958  1958 W Binder:1626_4: type=1400 audit(0.0:24): avc: denied { getattr } for path=/data/media dev=mmcblk0p54 ino=791521 scontext=u:r:radio:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
> sepolicy: fix radio denials

- system_app.te
06-30 15:05:41.156  3988  3988 W com.android.settings: type=1400 audit(0.0:15): avc: denied { call } for comm=4173796E635461736B202333 scontext=u:r:system_app:s0 tcontext=u:r:fingerprintd:s0 tclass=binder permissive=0
> sepolicy: fix fpc denials

- netmgrd.te
02-19 06:40:52.299   536   536 W netmgrd : type=1400 audit(0.0:4): avc: denied { create } for name=log.txt scontext=u:r:netmgrd:s0 tcontext=u:object_r:netmgr_data_file:s0 tclass=file permissive=0
> sepolicy: fix netmgrd denials

- netd.te
07-03 01:55:51.748  1058  1058 W netd    : type=1400 audit(0.0:4): avc: denied { read write } for path=socket:[127189] dev=sockfs ino=127189 scontext=u:r:netd:s0 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=unix_stream_socket permissive=0
> sepolicy: fix netd denials

- adbd.te
07-03 02:01:10.285 14331 14331 W /sbin/adbd: type=1400 audit(0.0:6): avc: denied { search } for comm=73657276696365203430 name=security dev=mmcblk0p54 ino=848641 scontext=u:r:adbd:s0 tcontext=u:object_r:security_file:s0 tclass=dir permissive=0
> sepolicy: fix adbd denials

- priv_app.te
07-05 18:14:37.887  7371  7371 W MtpServer: type=1400 audit(0.0:14): avc: denied { unlink } for name=48512031343720627920566974742E617669 dev=mmcblk1p1 ino=76 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vfat:s0 tclass=file permissive=0
> sepolicy: fix mtp denials

- file_contexts
- system_app.te
It is required for new DRS feature.
Change-Id: I0b26dad15fb6f220727a0aa2db227ada81c27e67
> [master] sony: sepolicy: Fix DRS denials

- system_app.te
[  121.476520] init: avc:  denied  { set } for property=debug.sf.nobootanimation pid=5265 uid=1000 gid=1000 scontext=u:r:system_app:s0 tcontext=u:object_r:boot_animation_prop:s0 tclass=property_service permissive=0
> sepolicy: let ES call soft reboot (bootanimation) for DRS

- priv_app.te
07-31 21:21:52.330 29683 29683 W d.process.media: type=1400 audit(0.0:1171): avc: denied { getattr } for path=/storage/3FE0-1616 dev=tmpfs ino=1480397 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:storage_stub_file:s0 tclass=dir permissive=0
> sepolicy: fix priv_app denial

- thermanager.te
on 4.4 smb symlinks from /sys/class/power_supply/battery/* to driver, allow thermanager reads it
03-26 17:30:18.719   543   543 W thermanager: type=1400 audit(0.0:4): avc: denied { read } for name=battery dev=sysfs ino=38037 scontext=u:r:thermanager:s0 tcontext=u:object_r:sysfs_battery_supply:s0 tclass=lnk_file permissive=0
> sepolicy: allow thermanager read lnk_file

- adbd.te
- addrsetup.te
- debuggerd.te
- fsck.te
- irsc_util.te
- lmkd.te
- logd.te
- mlog_qmi.te
- mm-qcamerad.te
- msm_irqbalanced.te
- netmgrd.te
- pad_controller.te
- peripheral_manager.te
- qmuxd.te
- rmt_storage.te
- sct.te
- sensors.te
- ta_qmi.te
- tad.te
- tfa_amp.te
- thermanager.te
- timekeep.te
- touchfusion.te
- ueventd.te
- vold.te
- wcnss_service.te
This is deprecated and, since Android 8.0, removed.
NOTE: All units touched by this commits WILL NEED to be fixed
properly.
> [SEPOLICY] Remove domain_deprecated from all units

- untrusted_app.te
some apps require perms to mount/unmount data from SD
> sepolicy: fix untrusted_apps denials

- file_contexts
update to generic /sys/class instead of /sys/devices with this we are sure all devices (included new coming) have power/charger sysfs labeled
> sepolicy: update power/charger sysfs

- file_contexts
We have moved these context declarations to platform-specific
repositories.
> Remove dev block nodes from common file_contexts

- bluetooth.te
- cnss-daemon.te
- device.te
- file_contexts
- pd_mapper.te
- property_contexts
- start_hci_filter.te
- tee.te
[*] Rework sysfs handling in cnss-deamon and pd_mapper, only allow access to subsystems
[*] Fix denials to bluetooth properties and dev/btpower
[*] allow tee system_admin permissions
> sepolicy: Fix bluetooth, WiFi and tee denials

- system_server.te
08-13 18:29:16.560  2633  2633 W Binder:776_8: type=1400 audit(0.0:107): avc: denied { read open } for path=/data/media/0/Android/data dev=mmcblk0p51 ino=971054 scontext=u:r:system_server:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
> sepolicy: fix system_server denials

- hal_light_default.te
09-17 13:28:44.987   546   546 W light@2.0-servi: type=1400 audit(0.0:1005): avc: denied { write } for name=brightness dev=sysfs ino=32235 scontext=u:r:hal_light_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
> sepolicy: avoid light denials

- priv_app.te
needed by apps like GMS (GoogleApp)
> sepolicy: let priv apps find hwservice_manager

- file_contexts
- hal_bluetooth_default.te
- hal_gnss_default.te
- start_hci_filter.te
let Global Navigation Satellite Systems (GNSS) read & write into /dev/vndbinder
09-17 21:24:13.959  6062  6062 W android.hardwar: type=1400 audit(0.0:1938): avc: denied { read write } for name="vndbinder" dev="tmpfs" ino=10923 scontext=u:r:hal_gnss_default:s0 tcontext=u:object_r:vndbinder_device:s0 tclass=chr_file permissive=0
09-17 21:37:02.229   635   635 W gnss@1.0-servic: type=1400 audit(0.0:26): avc: denied { read } for name="devices" dev="sysfs" ino=29502 scontext=u:r:hal_gnss_default:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
09-17 21:37:02.244  1336  1336 W Loc_hal_worker: type=1400 audit(0.0:35): avc: denied { create } for scontext=u:r:hal_gnss_default:s0 tcontext=u:r:hal_gnss_default:s0 tclass=socket permissive=0
09-17 21:47:34.436  1342  1342 W Loc_hal_worker: …
> sepolicy: avoid GNSS denials

- file_contexts
related with HDIL binder
09-18 08:40:40.138   591   591 W bluetooth@1.0-s: type=1400 audit(0.0:393): avc: denied { write } for name=extldo dev=sysfs ino=43895 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
> sepolicy: more maple denials

- audioserver.te
- bootanim.te
05-21 13:53:34.983   972   972 W AudioOut_D: type=1400 audit(0.0:4): avc: denied { call } for scontext=u:r:audioserver:s0 tcontext=u:r:bootanim:s0 tclass=binder permissive=0
05-21 13:53:34.984   980   980 W AudioOut_15: type=1400 audit(0.0:5): avc: denied { call } for scontext=u:r:audioserver:s0 tcontext=u:r:bootanim:s0 tclass=binder permissive=0
05-21 13:53:34.984   984   984 W AudioOut_1D: type=1400 audit(0.0:6): avc: denied { call } for scontext=u:r:audioserver:s0 tcontext=u:r:bootanim:s0 tclass=binder permissive=0
05-21 13:53:35.262  1027  1027 W BootAnimation::: type=1400 audit(0.0:7): avc: denied { read } for name="system" dev="sda15" ino=2457601 scontext=u:r:bootanim:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0
Signed-off-by: David Viteri …
> sepolicy: avoid bootanim audio denials

- hal_gnss_default.te
09-26 21:19:29.389  1455  1455 W Loc_hal_worker: type=1400 audit(0.0:101): avc: denied { add_name } for name=716D75785F636C69656E745F736F636B657420202031343535 scontext=u:r:hal_gnss_default:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=0
09-26 21:37:50.519  1125  1125 W Loc_hal_worker: type=1400 audit(0.0:66): avc: denied { create } for name=716D75785F636C69656E745F736F636B657420202031313235 scontext=u:r:hal_gnss_default:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=0
09-26 22:03:41.969  1178  1178 W Loc_hal_worker: type=1400 audit(0.0:61): avc: denied { write } for name="qmux_connect_socket" dev="tmpfs" ino=16903 scontext=u:r:hal_gnss_default:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=0
09-26 22:15:30.299  1295  1295 W …
> sepolicy: avoid qmuxd denials

- mm-qcamerad.te
This solves the camera avc denial selinux problem in Nougat 7.1.1
> Camera selinux denials

- crash_dump.te
- system_server.te
re-work for oreo and based on https://source.codeaurora.org/quic/la/device/qcom/sepolicy/tree/?h=LA.UM.6.4.r1-04000-8x98.0
> sepolicy: clean system_server

- mediaextractor.te
10-20 22:08:13.676  9062  9062 W generic : type=1400 audit(0.0:187): avc: denied { read } for path=/storage/emulated/0/DCIM/Camera/VID_20171020_220807.mp4 dev=sdcardfs ino=791570 scontext=u:r:mediaextractor:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0
> sepolicy: avoid mediaextractor denials

- mediaextractor.te
10-20 22:55:59.119  4603  4603 W Binder:616_5: type=1400 audit(0.0:33): avc: denied { getattr } for path=2F73746F726167652F656D756C617465642F302F5370696465726D616E20322E617669 dev="sdcardfs" ino=791573 scontext=u:r:mediaextractor:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0
> sepolicy: avoid more mediaextractor denials

- device.te
- file_contexts
- rdclean.te
Add ramdump partition block device type and set of rules for the
ramdump cleaner script. Each supported platform provides specific
block device label.
Signed-off-by: Oleksiy Avramchenko <oleksiy.avramchenko@sony.com>
> sepolicy: add ramdump cleaner rules

- audioserver.te
- cameraserver.te
- mediacodec.te
- system_server.te
11-02 20:35:17.192  1315  1315 W PhotonicModulat: type=1400 audit(0.0:7): avc: denied { write } for name=powerhal dev=tmpfs ino=10607 scontext=u:r:system_server:s0 tcontext=u:object_r:socket_device:s0 tclass=dir permissive=0
11-02 21:49:28.456   994   994 W system_server: type=1400 audit(0.0:4): avc: denied { add_name } for name="rqbsvr" scontext=u:r:system_server:s0 tcontext=u:object_r:socket_device:s0 tclass=dir permissive=0
11-02 21:56:28.524   984   984 W system_server: type=1400 audit(0.0:4): avc: denied { create } for name="rqbsvr" scontext=u:r:system_server:s0 tcontext=u:object_r:socket_device:s0 tclass=sock_file permissive=0
11-02 22:07:36.245   949   949 W system_server: type=1400 audit(0.0:4): avc: denied { setattr } for name="rqbsvr" dev="tmpfs" ino=19299 …
> sepolicy: avoid powerHAL denials

- rdclean.te
02-26 01:09:06.789   637   637 W dd      : type=1400 audit(0.0:15): avc: denied { search } for name=block dev=tmpfs ino=11424 scontext=u:r:rdclean:s0 tcontext=u:object_r:block_device:s0 tclass=dir permissive=0
> sepolicy: avoid rdclean denials

- system_server.te
11-07 22:15:31.368  5764  5764 W Binder:1011_12: type=1400 audit(0.0:99): avc: denied { write } for name=timerslack_ns dev=proc ino=68542 scontext=u:r:system_server:s0 tcontext=u:r:shell:s0 tclass=file permissive=0
> sepolicy: avoid sd denials

- addrsetup.te
- hal_bluetooth_default.te
This adds policy to allow the macaddrsetup service to write the WLAN MAC
address to a file, as well allowing the bluetooth service to read the BT
MAC file written by macaddrsetup.
> Fixes for creating MAC address files on Oreo

- system_server.te
11-19 23:20:43.044  1422  1422 W Loc_hal_worker: type=1400 audit(0.0:22601021): avc: denied { ioctl } for path=socket:[15838] dev=sockfs ino=15838 ioctlcmd=c302 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=socket permissive=0
11-19 23:47:53.859  1465  1465 W Loc_hal_worker: type=1400 audit(0.0:128): avc: denied { search } for name="netmgr" dev="tmpfs" ino=16586 scontext=u:r:system_server:s0 tcontext=u:object_r:netmgrd_socket:s0 tclass=dir permissive=0
11-19 23:58:21.889  1458  1458 W Loc_hal_worker: type=1400 audit(0.0:112): avc: denied { write } for name="netmgr_connect_socket" dev="tmpfs" ino=15637 scontext=u:r:system_server:s0 tcontext=u:object_r:netmgrd_socket:s0 tclass=sock_file permissive=0
11-20 00:03:19.649  1448  1448 W Loc_hal_worker: type=1400 …
> sepolicy: avoid gps denials

- hal_audio_default.te
- hal_fingerprint_default.te
- init.te
- mediacodec.te
- rmt_storage.te
Those permissions are based on kagura logs.
Enforcing mode still broken (random reboots) due to modem (at least kagura) and it needs more investigation.
> master: Address sepolicy denials

- init.te
avc: denied { write } for pid=1 comm="init" name="configuration"
dev="configfs" ino=10706 scontext=u:r:init:s0 tcontext=u:object_r:configfs:s0
Change-Id: Id81ab90db563296b7ad254710c501f21779bd1eb
> [master] sony: sepolicy: Address init denials

- file.te
- file_contexts
- genfs_contexts
Odmcheck will block init until exited. If a mismatch between odm partition and the build props is detected a warning screen will be shown. Currently this warning screen just has a simple placeholder UI with the version information shown on a blue background. The warning screen will be shown for 10 seconds, then the boot will resume regardless. Once everything is in place and works fine, after changing a build flag, odmcheck will instead shutdown the device after the 10 seconds.
> Initial odmcheck (2/4)

- rdclean.te
because of the apostrophe in the comment, the following warnings were
emitted during a build:
```
device/sony/sepolicy/rdclean.te:3:WARNING 'unrecognized character' at token ''' on line 22982:
'
#line 3
device/sony/sepolicy/rdclean.te:3:WARNING 'unrecognized character' at token ''' on line 22982:
'
#line 3
out/host/linux-x86/bin/checkpolicy:  loading policy configuration from out/target/product/maple/obj/ETC/sepolicy_intermediates/policy.conf
out/host/linux-x86/bin/checkpolicy:  policy configuration loaded
out/host/linux-x86/bin/checkpolicy:  writing binary representation (version 30) to out/target/product/maple/obj/ETC/sepolicy_intermediates/sepolicy.tmp
```
> Trivial: update comment to avoid syntax warning

- file_contexts
adapt rules from oreo so /odm/firmware and its contents are labelled
correctly.
also pick up rules for /vendor/firmware (symlink to /odm/firmware),
/firmware and /bt_firmware.  Note that /firmware and /bt_firmware were
already labelled correctly because context-mounts are used in the
fstab file.
> Label firmware files correctly when generating odm image

- fsck.te
- init.te
avc:  denied  { mounton } for  pid=461 comm="init" path="/dsp"
dev="rootfs" ino=8282 scontext=u:r:init:s0
tcontext=u:object_r:qdsp_file:s0 tclass=dir permissive=0
avc:  denied  { read } for  pid=480 comm="e2fsck" name="mmcblk0p32"
dev="tmpfs" ino=8823 scontext=u:r:fsck:s0
tcontext=u:object_r:adsprpcd_block_device:s0 tclass=blk_file permissive=0
Change-Id: Iae6778eb228dd8b3d88181ab7c63ff30b3fa3d63
> [master] sony: sepolicy: Address dsp denials

- genfs_contexts
12-10 23:44:24.287   643   643 I bluetooth@1.0-s: type=1400 audit(0.0:36): avc: denied { write } for name=state dev=sysfs ino=40854 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
12-11 00:01:47.200  1553  1553 I HwBinder:618_1: type=1400 audit(0.0:36): avc: denied { write } for name="extldo" dev="sysfs" ino=40843 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
> sepolicy: avoid qcom bt denials

- platform_app.te
11-23 21:38:31.704   553   553 E SELinux : avc:  denied  { find } for service=nfc pid=1302 uid=10029 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:nfc_service:s0 tclass=service_manager
> sepolicy: Allow nfc service access

- system_server.te
01-10 02:48:10.551  1032  1032 W android.bg: type=1400 audit(0.0:41): avc: denied { search } for name=location dev=sda66 ino=557059 scontext=u:r:system_server:s0 tcontext=u:object_r:location_data_file:s0 tclass=dir permissive=0
> sepolicy: avoid location denials

- system_server.te
01-10 02:48:10.551  1032  1032 W android.bg: type=1400 audit(0.0:41): avc: denied { search } for name=location dev=sda66 ino=557059 scontext=u:r:system_server:s0 tcontext=u:object_r:location_data_file:s0 tclass=dir permissive=0
> [master] sepolicy: avoid location denials

- system_app.te
01-10 13:30:30.582  4671  4671 W ndroid.settings: type=1400 audit(0.0:33): avc: denied { read } for name=version dev=proc ino=4026532109 scontext=u:r:system_app:s0 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
01-10 14:01:27.710  3815  3815 W ndroid.settings: type=1400 audit(0.0:33): avc: denied { open } for path="/proc/version" dev="proc" ino=4026532109 scontext=u:r:system_app:s0 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
> sepolicy: allow settings read kernel version

- system_server.te
latest aosp sepolicy allows such writes. The rules are based on:
https://android.googlesource.com/platform/system/sepolicy/+/5c41d40ecd3558d44861374c1c490676a224b488
All timerslack_ns related denies are covered by these rules.
Change-Id: Ie78facd3d3cfd2e0c190e03b53804ff098ae684a
> system_server: allow writing to timerslack_ns

- file_contexts
* '.' is a wildcard for any character, escaping it
makes sure that only 'sensors.qcom' is being labeled.
> sepolicy: Correct /odm/bin/sensors.qcom label

- appdomain.te
- hal_camera_default.te
12-11 11:21:33.905  8284  8284 I HwBinder:627_3: type=1400 audit(0.0:324): avc: denied { search } for name=powerhal dev=tmpfs ino=13663 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:powerhal_socket:s0 tclass=dir permissive=1
12-11 11:21:51.541 15721 15721 I id.GoogleCamera: type=1400 audit(0.0:326): avc: denied { open } for path=/dev/__properties__/u:object_r:camera_prop:s0 dev=tmpfs ino=14351 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=1
12-11 11:21:51.541 15721 15721 I id.GoogleCamera: type=1400 audit(0.0:327): avc: denied { getattr } for path=/dev/__properties__/u:object_r:camera_prop:s0 dev=tmpfs ino=14351 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=1
Signed-off-by: …
> sepolicy: avoid Gcam denials

- location.te
04-20 11:07:56.676   656   656 W pcid-lo : type=1400 audit(0.0:22359): avc: denied { search } for name=qmux_gps dev=tmpfs ino=3802 scontext=u:r:location:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=0
01-17 11:18:16.783   652   652 W pcid-lo : type=1400 audit(0.0:6869): avc: denied { write } for name="qmux_gps" dev="tmpfs" ino=3770 scontext=u:r:location:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=0
01-17 11:27:14.234   661   661 W pcid-lo : type=1400 audit(0.0:29): avc: denied { create } for name=716D75785F636C69656E745F736F636B657420202020363631 scontext=u:r:location:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=0
01-17 11:34:27.099   702   702 W pcid-lo : type=1400 audit(0.0:35): avc: denied { connectto } for …
> sepolicy: avoid location denials on loire

- system_app.te
01-19 12:52:05.260 11724 11724 W ndroid.settings: type=1400 audit(0.0:301): avc: denied { read } for name=enforce dev=selinuxfs ino=4 scontext=u:r:system_app:s0 tcontext=u:object_r:selinuxfs:s0 tclass=file permissive=0
> sepolicy: fix selinux status on settings

- file.te
- genfs_contexts
- init.te
- kernel.te
- radio.te
- system_server.te
- tad.te
label it using aosp selinux via domain_deprecated
https://android.googlesource.com/platform/system/sepolicy/+/android-8.1.0_r7/private/vold.te#2
https://android.googlesource.com/platform/system/sepolicy/+/android-8.1.0_r7/private/domain_deprecated.te#13
04-22 13:35:10.529   479   479 W vold    : type=1400 audit(0.0:5): avc: denied { read } for name=cmdline dev=proc ino=4026532141 scontext=u:r:vold:s0 tcontext=u:object_r:proc_cmdline:s0 tclass=file permissive=0
04-22 09:24:58.426   548   548 W tad_static: type=1400 audit(0.0:5): avc: denied { read } for name="cmdline" dev="proc" ino=4026532141 scontext=u:r:tad:s0 tcontext=u:object_r:proc:s0 tclass=file permissive=0
> sepolicy: do not label /proc/cmdline

- hal_gnss_qti.te
This solves the following denial on loire devices:
01-23 01:32:18.863 W/Loc_hal (1994): type=1400 audit(0.0:686): avc: denied { connectto } for path="/dev/socket/qmux_radio/qmux_connect_socket"
scontext=u:r:hal_gnss_qti:s0 tcontext=u:r:qmuxd:s0 tclass=unix_stream_socket permissive=0
Change-Id: I950cce33175c136d21bea5e9b57a487372e84f63
> sepolicy: allow gnss to connect to qmuxd sockets

- addrsetup.te
This adds policy to allow the macaddrsetup service to write the WLAN MAC
address to a file.
> sepolicy: Permit WLAN MAC address activity

- addrsetup.te
Reverts sonyxperiadev/device-sony-sepolicy#341
patch is already prezent upstream and can be cherry-picked ec9bc4a7554e54c7bf1a45a1a5b3e65cb429eb70
> Revert "sepolicy: Permit WLAN MAC address activity"

- charger.te
Fix sysfs_leds permission.
avc:  denied  { write } for  pid=465 comm="charger"
name="brightness" dev="sysfs" ino=39679 scontext=u:r:charger:s0
tcontext=u:object_r:sysfs_leds:s0 tclass=file permissive=0
Change-Id: Iedfef40f1d9ffe5b056887cc054a5921b3fa0b99
> [master] sony: selinux: Address charger denials

- system_server.te
This is an extension of d721910078caf4832389ee2cde48d276366d9ebd
latest aosp sepolicy allows such writes. The rules are based on:
https://android.googlesource.com/platform/system/sepolicy/+/5c41d40ecd3558d44861374c1c490676a224b488
All timerslack_ns related denies are covered by these rules.
avc: denied { write } for name="timerslack_ns" dev="proc"
ino=29102 scontext=u:r:system_server:s0
tcontext=u:r:hal_audio_default:s0 tclass=file permissive=0
Change-Id: I5d9a9a874cdb9ceee1a49e839a0858928884fc88
> [master] system_server: allow writing to timerslack_ns

- thermanager.te
Thermal should be able to find and write leds/backlight sysfs.
As logcat says
01-28 00:16:25.647   632   632 I thermanager: "backlight" set to level 0
The trigger for this patch:
avc: denied { search } for name="leds"
dev="sysfs" ino=21689 scontext=u:r:thermanager:s0
tcontext=u:object_r:sysfs_leds:s0 tclass=dir permissive=0
Also sort permissions alphabetically.
Change-Id: I8d63fd3f54190ec06d5d17ccc555febb13a96436
> [master] sony: sepolicy: Address thermanager denials

- netutils_wrapper.te
01-28 00:43:22.056  6686  6686 W iptables-wrappe: type=1400 audit(0.0:11): avc: denied { read write } for path=socket:[44513] dev=sockfs ino=44513 scontext=u:r:netutils_wrapper:s0 tcontext=u:r:netmgrd:s0 tclass=unix_stream_socket permissive=0
> sepolicy: avoid netmgr denials

- pd_services.te
05-21 13:40:44.259   627   627 W pd-mapper: type=1400 audit(0.0:5): avc: denied { read } for name=firmware dev=sda65 ino=2398 scontext=u:r:pd_mapper:s0 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
also use r_dir_file() macro instead of hardcoding rules
> sepolicy: avoid pd_mapper denials

- charger.te
avc:  denied  { dac_override } for  pid=453 comm="charger"
capability=1  scontext=u:r:charger:s0 tcontext=u:r:charger:s0
tclass=capability permissive=0
avc:  denied  { dac_read_search } for  pid=453 comm="charger"
capability=2  scontext=u:r:charger:s0 tcontext=u:r:charger:s0
tclass=capability permissive=0
avc:  denied  { syslog_read } for  pid=452 comm="charger"
scontext=u:r:charger:s0 tcontext=u:r:kernel:s0
tclass=system permissive=0
avc:  denied  { read } for  pid=451 comm="charger" name="/" dev="tmpfs"
ino=6450 scontext=u:r:charger:s0 tcontext=u:object_r:device:s0
tclass=dir permissive=0
avc:  denied  { write } for  pid=452 comm="charger" name="brightness"
dev="sysfs" ino=25413 scontext=u:r:charger:s0
tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=0
Signed-off-by: …
> [master] sony: sepolicy: Address charger denials

- property.te
- property_contexts
- system_app.te
selinux was removed in commit 14fe403ac06cdb2d1338795a9f6dc169f0a54f19 and it is needed for devices working under enforcing selinux
> sepolicy: re-add selinux for adboverwifi

- file.te
- file_contexts
- hal_wifi_default.te
03-15 11:27:28.095   633   633 W android.hardwar: type=1400 audit(0.0:38): avc: denied { write } for name=boot_wlan dev=sysfs ino=44284 scontext=u:r:hal_wifi_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
> sepolicy: avoid wlan denials

- property.te
- property_contexts
- system_app.te
This fixes:
[  174.166672] selinux: avc:  denied  { set } for property=persist.dispcal.setting pid=2319 uid=1000 gid=1000 scontext=u:r:system_app:s0 tcontext=u:object_r:default_prop:s0 tclass=property_service permissive=0\x0a
[  174.170856] init: sys_prop(PROP_MSG_SETPROP2): permission denied uid:1000 name:persist.dispcal.setting
Change-Id: I23a287f765a6fcb2e39016205c3e2848914a1b34
> sepolicy: Add rules for persist.dispcal.setting

- pd_services.te
[   12.422295] type=1400 audit(16689756.629:5): avc: denied { read } for pid=648 comm=pd-mapper name=firmware dev=sda65 ino=2420 scontext=u:r:pd_mapper:s0 tcontext=u:object_r:vendor_file:s0 tclass=dir permissive=0
support was removed in commit 0174e9cd3f0ceee90af83fd27b281aa4a2110319
> sepolicy: avoid pd_services denials

- file_contexts
* Since we switched to HIDL implementation we
got to label our new service so that it's able
to start.
Change-Id: I0b2efe50b77d70bd6b130047897823145c2193ab
> sepolicy: Label HIDL fingerprint HAL

- file_contexts
needed by akari (xz2) and apollo (xz2c)
> sepolicy: label gralloc & vulkan for 845

- hal_wifi_default.te
[   16.327338] type=1400 audit(1526281929.309:4): avc: denied { module_request } for pid=675 comm=android.hardwar kmod=net-pf-16-proto-16-family-cld80211 scontext=u:r:hal_wifi_default:s0 tcontext=u:r:kernel:s0 tclass=system permissive=0
> avoid wifi denials

- cashsvr.te
Properly fix the sysfs node permissions as well as assigning the proper uid to cash from inside cash.
Change-Id: Idcfd79afe55a50084e98f16f29c30f5ca4f426d5
> [DNM] cash: setup selinux for new permissions management

- file_contexts
all the things were move to /data/vendor/netmgr and we should not add permissions
for the old location
> sepolicy: remove legacy /data/misc/netmgr folder

- recovery.te
poplar:/cache/recovery # cat last_kmsg | grep avc
<5>[    1.768711] audit: type=1400 audit(24497544.774:5): avc:  denied  { search } for  pid=530 comm=recovery name=c900000.qcom,mdss_mdp dev=sysfs ino=24070 scontext=u:r:recovery:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=dir permissive=0
<5>[   27.251991] audit: type=1400 audit(24497570.257:6): avc:  denied  { search } for  pid=567 comm=mke2fs_static name=features dev=sysfs ino=32760 scontext=u:r:recovery:s0 tcontext=u:object_r:sysfs_fs_ext4_features:s0 tclass=dir permissive=0
<5>[   29.808838] audit: type=1400 audit(24500789.794:5): avc:  denied  { read } for  pid=583 comm="mke2fs_static" name="lazy_itable_init" dev="sysfs" ino=32761 scontext=u:r:recovery:s0 tcontext=u:object_r:sysfs_fs_ext4_features:s0 tclass=file permissive=0 …
> sepolicy: avoid recovery denials

- system_app.te
06-16 00:10:29.977 10073 10073 W xtendedsettings: type=1400 audit(0.0:29): avc: denied { write } for name=mode dev=sysfs ino=34050 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_graphics:s0 tclass=file permissive=0
> sepolicy: avoid DRS denials

- hal_wifi_supplicant_default.te
- netd.te
> sepolicy: avoid kernel 4.9 denials

- file.te
those are already defined on https://android.googlesource.com/platform/system/sepolicy/+/android-9.0.0_r1/public/file.te
> sepolicy: remove double def

- file.te
- genfs_contexts
- init-devstart-sh.te
- init.te
- msm_irqbalanced.te
- netd.te
- tad.te
- zygote.te
This pull request contains cleanups and comments to finish off cherry-picking #396.
Regressions from previous *WIP* pull request that need to be addressed outside of the SEPolicy:
- msm_irqbalance with `DAC_OVERRIDE` permission:
Granting this permission is not allowed anymore since Pie, and not even needed. The init script starts the process as root user, and all the files it needs to access are owned by root with permission `600`.
The capset call it does to acquire DAC_OVERRIDE (`capset({version=_LINUX_CAPABILITY_VERSION_1, pid=0}, {effective=1<<CAP_DAC_OVERRIDE, permitted=1<<CAP_DAC_OVERRIDE, inheritable=0}) = 0`) can thus be removed entirely.
However, every once in a while the init script starts the executable with group and user `nobody`, which might explain the initial reason to use …
> Pie/4.9: Sepolicy cleanups

- addrsetup.te
- rild.te
- sensors.te
- timekeep.te
These commits fix a bunch of regressions caused by removing "erroneous" lines after enabling `PRODUCT_FULL_TREBLE` (through setting `PRODUCT_SHIPPING_API_LEVEL`).
All commits succeed `m sepolicy_tests` with `PRODUCT_SHIPPING_API_LEVEL` set to either `26` or `27`.
There are still more regressions left to fix which require modifications to closed-source oem images; a common one being vendor applications not allowed access to `binder` anymore.
> FULL_TREBLE regression fixes

- vendor_init.te
avc: denied { setattr } for pid=430 comm="init" name="audio" dev="dm-1"
ino=188094 scontext=u:r:vendor_init:s0 tcontext=u:object_r:audio_data_file:s0
tclass=dir permissive=0
avc: denied { setattr } for pid=430 comm="init" name="bluetooth" dev="tmpfs"
ino=2938 scontext=u:r:vendor_init:s0 tcontext=u:object_r:bluetooth_data_file:s0
tclass=dir permissive=0
avc: denied { setattr } for pid=430 comm="init" name="dhcp" dev="tmpfs" ino=2962
scontext=u:r:vendor_init:s0 tcontext=u:object_r:dhcp_data_file:s0 tclass=dir
permissive=0
avc: denied { write } for pid=430 comm="init" name="/" dev="tmpfs" ino=17429
scontext=u:r:vendor_init:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir
permissive=0
avc: denied { setattr } for pid=430 comm="init" name="wifi" dev="tmpfs" ino=2958 …
> sony: sepolicy: Address vendor_init denials

- vendor/charger.te
`healthd` already has `sysfs_batteryinfo` caps and `charger` should use them them as well.
This is needed for accessing `/sys/devices/platform/soc/75b9000.i2c/i2c-11/11-0025/power_supply/typec/type` on tone for which I have specified `sysfs_batteryinfo` in https://github.com/sonyxperiadev/device-sony-tone/pull/150.
<strike>The `wake_alarm` capability may not be needed in normal operation, I have only seen it requested in conjunction with fpc crashes. Please discuss.</strik>
> Add batteryinfo capabilities to charger

- vendor/addrsetup.te
03-09 09:49:18.239   951   951 I macaddrsetup: type=1400 audit(0.0:27): avc: denied { create } for scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=udp_socket permissive=1
03-09 09:49:18.239   951   951 I macaddrsetup: type=1400 audit(0.0:28): avc: denied { net_raw } for capability=13 scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=capability permissive=1
03-09 09:49:18.239   951   951 I macaddrsetup: type=1400 audit(0.0:30): avc: denied { net_admin } for capability=12 scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=capability permissive=1
> addrsetup: avoid selinux denials for brcmfmac

- vendor/addrsetup.te
03-09 09:49:18.239   951   951 I macaddrsetup: type=1400 audit(0.0:27): avc: denied { create } for scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=udp_socket permissive=1
> addrsetup: avoid selinux denials

- vendor/file_contexts
need to maintain the backward compatibility and avoid errors in build
> sepolicy: label fs as rootfs

- vendor/addrsetup.te
- vendor/cameraserver.te
- vendor/cashsvr.te
- vendor/file.te
- vendor/file_contexts
- vendor/genfs_contexts
- vendor/hal_camera_default.te
- vendor/hal_gnss_qti.te
- vendor/hal_sensors_default.te
- vendor/hal_wifi_supplicant_default.te
- vendor/init-devstart-sh.te
- vendor/netmgrd.te
- vendor/per_mgr.te
- vendor/per_proxy.te
- vendor/property.te
- vendor/property_contexts
- vendor/sensors.te
- vendor/wcnss_service.te
Dumping this here so we can discuss what is actually needed.
> Vendor updates for Pie: Sensors, Wi-Fi, properties

- vendor/hal_bluetooth_default.te
- vendor/property_contexts
- vendor/qcrilam_app.te
- vendor/rild.te
- vendor/seapp_contexts
- vendor/system_app.te
- vendor/timekeep.te
- vendor/timekeep_app.te
- vendor/vndservice.te
- vendor/vndservice_contexts
More porting from my [broad-updates](https://github.com/ix5/device-sony-sepolicy/tree/broad-updates) branch, with nice atomic commits.
Will change title once it is ready to merge.
> Vendor updates for Pie: Bluetooth, own domain for SODP apps

- vendor/per_mgr.te
- vendor/per_proxy.te
- vendor/service.te
- vendor/service_contexts
- vendor/vndservice.te
- vendor/vndservice_contexts
vendor.qcom.PeripheralManager, pm-proxy and pm-service are not yet using vndbinder and their services cannot be accessed as a `vndservice_manager_type`.
Temporarily switch their labels to non-vendor types and change the binder-related labels as well.
Note: vendor.qcom.PeripheralManager needs to be labeled as a regular `service_manager_type`, else it will not be recognized correctly and instead be assigned `default_android_service`.
> [WIP] PeripheralManager: Re-label as non-vendor type (temporarily), fix denials

- vendor/appdomain.te
- vendor/cameraserver.te
- vendor/hal_camera_default.te
Macros make our policy more readable. `set_prop` includes `get_prop` already.
All sorts of domains request access to `vendor_camera_prop` and granting read-only access should be harmless.
> vendor_camera_prop: appdomain access, cleanup

- vendor/file_contexts
The new service can share the same domain as the default service.
Since the qti service has more permissions, rules will need to be added for them.
> vendor: label bluetooth qti service as hal_bluetooth_default_exec

- LICENSE.md
- README.md
3-clause BSD is what most projects use for sepolicy, c.f. [CodeAurora](https://source.codeaurora.org/quic/la/device/qcom/sepolicy/tree/common/hal_perf_default.te?h=LA.UM.6.3.r4-05900-sdm845.0).
Formatting tips help to how to order policy statements.
> Add license, formatting tips

- sepolicy.mk
Rename `BOARD_SEPOLICY_DIRS` to `BOARD_VENDOR_SEPOLICY_DIRS` for the `vendor/` subfolder.
See system/sepolicy/Android.mk:
> BOARD_SEPOLICY_DIRS was used for vendor/odm sepolicy customization before.
> It has been replaced by BOARD_VENDOR_SEPOLICY_DIRS (mandatory) and
> BOARD_ODM_SEPOLICY_DIRS (optional). BOARD_SEPOLICY_DIRS is still allowed for
> backward compatibility, which will be merged into BOARD_VENDOR_SEPOLICY_DIRS.
```
ifdef BOARD_SEPOLICY_DIRS
BOARD_VENDOR_SEPOLICY_DIRS += $(BOARD_SEPOLICY_DIRS)
endif
```
There are, however, [some remnants where `BOARD_SEPOLICY_DIRS` is used explicitly](https://android.googlesource.com/platform/system/sepolicy/+/android-9.0.0_r22/Android.mk#285), and this can mess with rules. So better do it properly here and not get caught by erroneous …
> [1/3] sepolicy.mk: Fix legacy build variable

- vendor/timekeep.te
- vendor/timekeep_app.te
`timekeep.c` never dropped root privileges, so `{fowner}` was wrong.  
Now the program runs outfitted with `CAP_SYS_TIME` via `init.rc` and only needs `{sys_time}` caps in sepolicy.
The `open()` call in` timekeep.c` will traverse parent folders of the target path as well to resolve the `rtc` symlink. (It points from e.g. `/sys/class/rtc/rtc0/since_epoch` to `/sys/device/platform/[...]/rtc/rtc0/since_epoch`)
Same goes for the Java app.
> Timekeep:  Drop fowner cap, search msm_subsys

- vendor/file.te
- vendor/file_contexts
- vendor/hal_health_default.te
- vendor/healthd.te
Since `android.hardware.health@2.0-service.sony` replaces `healthd` and the AOSP policy is barebones, add the needed permissions for our new HAL.
Permissions are a small subset of what Pixel HALs use.
Label `/mnt/vendor/persist/battery/` folder:  
Naming follows crosshatch sepolicy, except we mount `/persist/` under `/mnt/vendor/persist/`.
> Label new health HAL and add permissions

- vendor/vendor_init.te
This is needed for the .rc file shipped with the new health HAL.
vendor_init needs permissions to create and chown the /(mnt/vendor/)persist/battery/ folder
Fix the following denial:
- vendor_init:
avc: granted { setattr } for name="battery" dev="mmcblk0p44" ino=48 \
scontext=u:r:vendor_init:s0 tcontext=u:object_r:persist_battery_file:s0 tclass=dir
> vendor_init: Allow creating /persist/battery/

- vendor/wcnss_service.te
Permissions for /data/vendor/wifi/{hostapd,wpa}/* were granted in 3b87ba2d18eb88892ef9300cfd8243b520361442 "/data/vendor/wifi/*: Switch to default AOSP labels"
But they were never used, wcnss only wants to read /data/vendor/wifi/wlan.bin.
(@alviteri please confirm)
> wcnss: Remove unused permissions

- vendor/hal_bluetooth_default.te
following CAF
https://source.codeaurora.org/quic/la/device/qcom/sepolicy/tree/vendor/common/hal_bluetooth_qti.te?h=LA.UM.7.3.r1-06600-sdm845.0#n49
avoid
01-05 00:12:43.409   718   718 I HwBinder:718_1: type=1400 audit(0.0:198): avc: denied { search } for name=vendor dev=tmpfs ino=21530 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:mnt_vendor_file:s0 tclass=dir permissive=1
> avoid bt-qti denials

- private/service_contexts
- public/service.te
- vendor/per_mgr.te
- vendor/per_proxy.te
- vendor/rild.te
- vendor/vndservice.te
- vendor/vndservice_contexts
- vendor/wcnss_service.te
vendor.qcom.PeripheralManager, pm-proxy and pm-service are not yet using vndbinder and thus do not get picked up as vndservices.
Since PeripheralManager thus is a regular platform service in Android's eyes, its policy needs to be defined in the "private"(=platform) policy.  Any label assigned to it in vndservice_contexts will be ignored and vendor.qcom.PeripheralManager will thus be labeled according to a wildcard as default_android_service.
Because of the split sepolicy for full-treble devices (meaning the policy no longer resides in rootfs of boot.img as {vendor,plat}_service_contexts and the "sepolicy" binary representation also moves into two parts inside /{system,vendor}/etc/sepolicy/), platform/framework and vendor can no longer share access to a "service_manager_type" definition in …
> PeripheralManager: Re-label as non-vendor type [LITE]

- vendor/property_contexts
The property has been renamed from `sys.listeners.registered` to `vendor.sys.listeners.registered`.
Leave the old prop in until the migration is complete.
avc:  denied  { set } for property=vendor.sys.listeners.registered pid=489 \
uid=1000 gid=1000 scontext=u:r:tee:s0 tcontext=u:object_r:vendor_default_prop:s0 tclass=property_service
> tee: Update label for listener prop

- vendor/per_mgr.te
dontaudit module_request: Follow crosshatch sepolicy and ignore:
https://android.googlesource.com/device/google/crosshatch-sepolicy/+/android-9.0.0_r30/vendor/qcom/common/per_mgr.te#26
Denial:
avc: denied { module_request } for comm="pm-service" kmod="net-pf-42" scontext=u:r:per_mgr:s0 tcontext=u:r:kernel:s0 tclass=system
Allow searching for devices
Denial:
avc: denied { search } for comm="pm-service" name="/" dev="tmpfs" \
ino=13798 scontext=u:r:per_mgr:s0 tcontext=u:object_r:device:s0 tclass=dir
> [WIP] per_mgr: Search, dontaudit module_request

- private/dnsmasq.te
Happens while tethering.
This is an android bug we have to work around.
avc: denied { getattr } for comm="dnsmasq" path="pipe:[19380]"
dev="pipefs" ino=19380 scontext=u:r:dnsmasq:s0 tcontext=u:r:netd:s0 tclass=fifo_file permissive=1 b/77868789
avc: denied { getattr } for path="pipe:[19380]"
dev="pipefs" ino=19380 scontext=u:r:dnsmasq:s0 tcontext=u:r:netd:s0 tclass=fifo_file permissive=1 b/77868789
avc: denied { getattr } for comm="dnsmasq" path="socket:[19388]"
dev="sockfs" ino=19388 scontext=u:r:dnsmasq:s0 tcontext=u:r:netd:s0 tclass=unix_stream_socket permissive=1 b/77868789
avc: denied { getattr } for path="socket:[19388]"
dev="sockfs" ino=19388 scontext=u:r:dnsmasq:s0 tcontext=u:r:netd:s0 tclass=unix_stream_socket permissive=1 b/77868789
> dnsmasq: Allow access to netd (b/77868789)

- vendor/genfs_contexts
avoid
01-23 23:46:19.699  5439  5439 W xtendedsettings: type=1400 audit(0.0:190): avc: denied { write } for name=pcc_profile dev=sysfs ino=51797 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
> label sys/devices/dsi_panel_driver/pcc_profile as sysfs_pcc_profile

- vendor/system_app.te
01-23 23:46:31.749  1512  1512 W com.android.settings: type=1400 audit(0.0:198): avc: denied { call } for comm=4173796E635461736B202333 scontext=u:r:system_app:s0 tcontext=u:r:update_engine:s0 tclass=binder permissive=0
> avoid system_app denials

- vendor/property_contexts
[   33.416196] selinux: avc:  denied  { set } for property=persist.vendor.bt.soc.scram_freqs pid=698 uid=1002 gid=1002 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:vendor_default_prop:s0 tclass=property_service permissive=0\x0a
> avoid bt denials

- vendor/hal_health_default.te
5-19 20:30:20.697   651   651 I android.hardwar: type=1400 audit(0.0:7): avc: denied { read } for name=type dev=sysfs ino=39407 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=file permissive=1
05-19 20:30:20.697   651   651 I android.hardwar: type=1400 audit(0.0:8): avc: denied { open } for path=/sys/devices/platform/soc/c176000.i2c/i2c-2/2-001d/power_supply/parallel/type dev=sysfs ino=39407 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=file permissive=1
05-19 20:30:20.697   651   651 I android.hardwar: type=1400 audit(0.0:9): avc: denied { getattr } for path=/sys/devices/platform/soc/c176000.i2c/i2c-2/2-001d/power_supply/parallel/type dev=sysfs ino=39407 scontext=u:r:hal_health_default:s0 …
> avoid health denials

- vendor/hal_health_default.te
For restoring `charge_full` and `cycle_count`, write access is also needed.
Denial:
`avc: denied { write } for name="charge_full" dev="sysfs" ino=42624 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_batteryinfo:s0 tclass=file`
> health: Allow restoring battery stats

- vendor/wcnss_service.te
Should be removed along with #446 / 03f39079fa25c3aa3630f502a3403baf2c14d3b1 when PeripheralManager is eventually fixed.
Denial(on apollo):
`avc: denied { call } for scontext=u:r:wcnss_service:s0  tcontext=u:r:servicemanager:s0 tclass=binder`
> wcnss_service: Allow platform binder in non-treble

- vendor/file_contexts
For vendor v5, the file was renamed from `vulkan.$platform.so` to `vulkan.qcom.so`
> file_contexts: Update vulkan lib path

- vendor/hal_sensors_default.te
- vendor/sensors.te
Tested on tone/kagura, please also check on other platforms if this can safely be merged.
`sensors`: Access to sysfs has been specified in more granularity in previous commits, now lock it down.
Read-only access to chr_device is sufficient.
`hal_sensors_default`: dontaudit module_request. The dontaudit for module_request is in accordance with crosshatch sepolicy:
https://android.googlesource.com/device/google/crosshatch-sepolicy/+/android-9.0.0_r30/vendor/qcom/common/hal_sensors_default.te#22
> [WIP] Sensors: Reduce permissions

- vendor/cashsvr.te
- vendor/file.te
- vendor/file_contexts
- Add label for cashsvr data folder
- Reorder the data folders alphabetically as well
- Save calibration from Misc-TA to data dir
Changes brought by: sonyxperiadev/vendor-sony-oss-cash#11:
cashsvr communicates over sockets with the tad daemon to get calibration data from the Misc-TA partition.
It then saves that calibration data to `/data/vendor/cashsvr/*` and reads it at successive startups.
- cashsvr: Label ToF/SPAD sysfs nodes: This is needed to set ToF and RGBC-IR calibrations from userspace
> [WIP] cash changes for reading/writing calibration

- vendor/service.te
- vendor/service_contexts
The com.sony.TimeKeep Java app never starts any kind of service, it only receives broadcasts.
The label was never used and can thus be removed from sepolicy.
> Remove unused timekeep_service label

- BUGSs.md
- private/system_server.te
Android bug to work around until fixed upstream.
Denial:
avc:  denied  { find } for service=thermalservice pid=1113 \
uid=1000 scontext=u:r:system_server:s0 \
tcontext=u:object_r:thermal_service:s0 tclass=service_manager
> system_server: Find thermalservice (b/124102550)

- vendor/appdomain.te
- vendor/genfs_contexts
Crosshatch sepolicy labels thermals this way as well.
**EDIT:**
Allow `appdomain`(which encompasses all apps) to read thermals from `sysfs_thermal`.
<strike>Helps with certain apps trying to read thermal values through /sys/class instead of /sys/devices/virtual</strike>
> Label /sys/class/thermal and allow app access

- vendor/untrusted_app_all.te
Dependent on https://github.com/sonyxperiadev/device-sony-sepolicy/pull/471
> Allow apps to access thermal data

- vendor/genfs_contexts
Crosshatch sepolicy does it this way as well.
Helps with certain apps trying to read thermal values through /sys/class instead of /sys/devices/virtual
> genfs_contexts: Label /sys/class/thermal

- adsprpcd.te
- cdsprpcd.te
- file.te
- file_contexts
- init.te
We can reuse the adsprpcd_file label and simplify the rules
Why backport to o-mr1? Some devices are still stuck on Oreo. Once someone decides to upgrade them to Pie, they will have issues because we did the change back to `adsprpcd_file` on Pie already.
This change preempts any issues. File relabeling is still allowed on Oreo, so this change should be fine.
> [o-mr1] dsp: Rename qdsp_file to adsprpcd_file

- vendor/hal_audio_default.te
Denial:
`avc: denied { call } for comm="writer" scontext=u:r:hal_audio_default:s0 
tcontext=u:r:hal_power_default:s0 tclass=binder`
(Also prettify the access to `sysfs_soc`)
> hal_audio_default: Call powerhal over binder

- vendor/shell.te
Allow non-root to tune powerhal and CASH via setting props.
Dependent on https://github.com/sonyxperiadev/device-sony-sepolicy/pull/476 for the powerhal prop label
> shell: tune powerhal and CASH via props

- cashsvr.te
- file.te
- file_contexts
- ucommsvr.te
Built on `r52`, no rules violated.
> [o-mr1] Backport cashsvr, ucommsvr policy changes

- BUGSs.md
- private/crash_dump.te
- vendor/file.te
The file descriptor for the resource cache file seems to be leaking, so access to it is not the correct solution.
See Nick Kralevich's comment on [r.android.com/867710](https://r.android.com/867710)
`sysfs_clkscale` and `sysfs_timekeep` weren't used anywhere, not even in platform sepolicy.
> Cleanup unused file types and remove private crash_dump policy

- vendor/wcnss_service.te
Access to kernel modules is not needed.
> wcnss: dontaudit module_request

- vendor/file.te
- vendor/tad.te
Same as /data/hlos_rfs, tad now creates and uses files in /data/vendor/hlos_rfs.
The type_transition rule means any files/dirs tad creates in /data/vendor will use the rfs_file label.
When the broader type_transition rule without "hlos_rfs" as the object_name at the end is in place, no need to specify hlos_rfs again.
See https://selinuxproject.org/page/TypeStatements
`type_transition source_type target_type : class default_type object_name;`
> [WIP] tad: Control /data/vendor/hlos_rfs/ files

- vendor/property.te
- vendor/property_contexts
This is needed for accessing ro.wifi.addr_path
Why not re-use AOSP's regular "wifi_prop" label?
wifi_prop is reserved for platform/coredomain access, but we want vendor programs like macaddrsetup to use it.
> Label ro.wifi. props

- vendor/addrsetup.te
If compiled with `BRCFMAC`, `macaddrsetup` uses an `ioctl` to get the WLAN mac address, see
https://github.com/sonyxperiadev/macaddrsetup/blob/d413798801a15dc5633b2beb17852d39e608dc0a/macaddrsetup.c#L154
The ioctl is already defined in AOSP sepolicy so we can set it using `allowxperm`.
> addrsetup: Allow SIOCSIFHWADDR ioctl

- vendor/cdsprpcd.te
- Allow `ioctl` to `ion_device`
- Allow reading `vendor_file` dirs
> cdsprpcd: ioctl to ion_device, read vendor_file dirs

- vendor/sscrpcd.te
- Prettify: Arrange perms logically
- Allow more file and device access (not all denials listed, but they were tested on tama by Alin)
- `dontaudit module_request`
> sscrpcd: Allow more file+device access, dontaudit module_request

- vendor/file.te
- vendor/file_contexts
- vendor/vendor_init.te
- Label `/sys/block/*/queue/*`
A broad regex was chosen as not to clash with omni's sepolicy which uses sysfs_block_scheduler.
See https://gerrit.omnirom.org/c/android_vendor_omni/+/33309
- vendor_init: Write disk queue parameters
tama's (and yoshino's) `rootdir/vendor/etc/init/init.$DEVICE.rc` writes to `/sys/block/sd[ab]/queue` since device-sony-tama@93f8d1dbcd7b1eb69dcc7fed4040f0ce295a301f
> vendor_init: Label and access more proc+sysfs files

- vendor/file_contexts
On devices using the 7.3 display hal, an additional gralloc library exists.
The library is accessed by surfaceflinger similar to libgrallocutils, so make it have the same context.
> vendor: file_contexts: add libgralloccore

- README.md
In the spirit of clear guidance and cleaning up old cruft, start by laying out rules more clearly.
> README: Expand policy syntax recommendations

- BUGSs.md
- vendor/file.te
- vendor/file_contexts
- vendor/hal_audio_default.te
- vendor/hal_gatekeeper_qti.te
- vendor/hal_graphics_composer_default.te
- vendor/hal_keymaster_qti.te
- vendor/netmgrd.te
- vendor/system_server.te
- vendor/te_macros
- macros: Add Q compatibility macros
- `hal_audio_default`: Reorder items
- `hal_gatekeeper_qti`: Use `get_prop` macro
- `hal_keymaster_qti`: Use `get_prop` macro
- `netmgrd`: Prettify policy, reorder items and clean up syntax
- netmgrd: Remove superfluous `get_prop`
`wakelock_use()` already grants `get_prop($1, hwservicemanager_prop)`
- `BUGS`: Add note about netmgrd & netutils
- `netmgrd`: Add violator for vendor_file access
The `vendor_executes_system_violators` attribute name is a bit misleading since it exempts all file operations from the neverallow, not only {execute}.
- `system_server`: Reorder items
- Use AOSP labels for keylayout and idc files
- `hal_graphics_composer`: Use macros, reorder
- `hal_graphics_composer`: Client domain for hal_graphics_allocator
> Q compatibility and cleanup

- vendor/netmgrd.te
This reverts commit aabf2fe740e5e397aa9adb1272134ed6531be26d.
The wakelock_use() macro only includes `get_prop($1, hwservicemanager_prop)` in Android Q but not yet in Pie
(Thx Marijn)
> Revert "netmgrd: Remove superfluous get_prop"

- BUGSs.md
- README.md
- vendor/file.te
- vendor/file_contexts
- vendor/hal_audio_default.te
- vendor/hal_gatekeeper_qti.te
- vendor/hal_graphics_composer_default.te
- vendor/hal_keymaster_qti.te
- vendor/netmgrd.te
- vendor/system_server.te
- README: Update statement order
- `hal_audio_default`: Reorder items
- `hal_gatekeeper_qti`: Use `get_prop` macro (needed for Q)
- `hal_keymaster_qti`: Use `get_prop` macro  (needed for Q)
- `netmgrd`: Prettify policy, reorder items and clean up syntax
- `netmgrd`: Add violator for vendor_file access
The `vendor_executes_system_violators` attribute name is a bit misleading since it exempts all file operations from the neverallow, not only {execute}.
(Only for non-full-treble, have to find a proper solution soon)
- `system_server`: Reorder items
- Use AOSP labels for `keylayout` and `idc` files
- `hal_graphics_composer`: Use macros, reorder
- `hal_graphics_composer`: Client domain for `hal_graphics_allocator`
> Q compatability improvements and cleanup

- vendor/hal_audio_default.te
- vendor/hal_graphics_composer_default.te
The graphics and audio HAL are already part of the allocator and power manager client domain, respectively. There is no need to grant them the `find` and `call` rights again.
Also address a denial regarding reading `/mnt/vendor/persist/display`.
> Q cleanup: Remove dupplicate allows, allow display access to /mnt/vendor/persist/display

- vendor/file.te
- vendor/file_contexts
- vendor/tee.te
This change allows Egistec fingerprint sensors to be used with enforcing sepolicy.
Tested on Discovery with full treble and split-sepolicy enabled.
> tee: Label /data/misc/egistec and grant tee access.

- BUGSs.md
- vendor/cameraserver.te
- vendor/file_contexts
- vendor/keystore.te
- vendor/netmgrd.te
- vendor/property.te
- vendor/property_contexts
- vendor/rild.te
- vendor/thermalserviced.te
- vendor/usbd.te
- vendor/vendor_init.te
- Label `rild.*` and `vendor.rild.*` props and allow access
- Update label for `persist.net.doxlat`; the prop is renamed in `netmgrd` for v7 Software Binaries.
Also stop using the `net_radio_prop` coredomain label for a vendor prop.
- Label camera and audio libs as sp-hal
Ideally, `audioserver` and `cameraserver` should not access vendor files at all, but until that is fixed, label the hw libs as `same_process_hal` so that both system and vendor programs have access.
- `cameraserver`: Access `video_device`
- Allow searching `/system` dirs to some coredomains: `keystore`, `thermalserviced` and `usbd` are legacy domains which seem to be using wrong modes for searching system files.
> [WIP] v7 Quick Fixes: rild prop name, netmgrd, cameraserver, audioserver, legacy /system

- vendor/hal_wifi_default.te
- vendor/kernel.te
These commits address new denials introduced after cherry-picking https://github.com/sonyxperiadev/device-sony-sepolicy/pull/480. which relabels `/d/wlan{,0}/` to `debugfs_wlan`.
Userdebug builds do not regulate access to `debugfs`, so these are only found after making the labels on those files more specific.
> WiFi debugfs denials

- vendor/netmgrd.te
AOSP sepolicy has this since 2017:
`netutils_wrapper.te`
```
domain_auto_trans({
domain -coredomain -appdomain
}, netutils_wrapper_exec, netutils_wrapper)
```
> [WIP] Remove dupe domain_auto_trans for netutils_wrapper

- vendor/domain.te
- vendor/hal_bluetooth_default.te
- vendor/hal_gnss_qti.te
- vendor/hal_sensors_default.te
- vendor/netmgrd.te
- vendor/sensors.te
`hal_sensors_default`, `hal_gnss_qti`, `netmgrd` and `sensors` should only receive access to `/dev/diag` in `userdebug` or `eng` builds and all other access should be ignored.
> Regulate /dev/diag access in user builds

- vendor/hal_bluetooth_default.te
In order to read or write to /dev/diag, the file needs to be opened in
the first place. Use rw_file_perms to simplify the access.
Adresses:
W bluetooth@1.0-s: type=1400 audit(0.0:71): avc: denied { open } for path="/dev/diag" dev="tmpfs" ino=17553 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file
E Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
E vendor.qti.bluetooth@1.0-diag_interface: Failed to Init diag
E Diag_Lib: diag: In diagpkt_tbl_reg, service not initialized.
NOTE: Even though the HAL "says" it initializes fine in the logs, it
actually fails later on, leaving Bluetooth dysfunctional. In turn, the
system counterpart crashes for not being able to locate the service.
> hal_bluetooth_default: Allow opening diag_device in userdebug/eng.

- vendor/addrsetup.te
macaddrsetup works fine without loading kernel modules
Denial:
`avc: denied { module_request } for comm="macaddrsetup" kmod="netdev-wlan0" context=u:r:addrsetup:s0 tcontext=u:r:kernel:s0 tclass=system`
> [WIP] addrsetup: Ignore kernel module request

- vendor/wificond.te
Denial:
`avc: denied { open } for comm="wificond" path="/system/lib64/hw" dev="mmcblk0p55" ino=1658 context=u:r:wificond:s0 tcontext=u:object_r:system_file:s0 tclass=dir`
> [WIP] wificond: Access system files

- vendor/system_app.te
Denials:
```
avc: denied { bind } for comm="UEventObserver" scontext=u:r:system_app:s0 \
tcontext=u:r:system_app:s0 tclass=netlink_kobject_uevent_socket
avc: denied { create } for comm="UEventObserver" scontext=u:r:system_app:s0 \
tcontext=u:r:system_app:s0 tclass=netlink_kobject_uevent_socket
avc: denied { read } for comm="UEventObserver" scontext=u:r:system_app:s0 \
tcontext=u:r:system_app:s0 tclass=netlink_kobject_uevent_socket
avc: denied { setopt } for comm="UEventObserver" scontext=u:r:system_app:s0 \
tcontext=u:r:system_app:s0 tclass=netlink_kobject_uevent_socket
```
> system_app: Allow creating netlink sockets

- vendor/vendor_init.te
Policy for https://github.com/sonyxperiadev/device-sony-common/pull/601
Denials:
avc: denied { getattr } for comm="init" path="/mnt/vendor/persist/sensors" \
dev="mmcblk0p44" ino=12 scontext=u:r:vendor_init:s0 \
tcontext=u:object_r:unlabeled:s0 tclass=dir
avc: denied { relabelfrom } for comm="init" name="sensors" \
dev="mmcblk0p44" ino=12 scontext=u:r:vendor_init:s0 \
tcontext=u:object_r:unlabeled:s0 tclass=dir
avc: denied { getattr } for comm="init" \
path="/mnt/vendor/persist/sensors/sensors_settings" dev="mmcblk0p44" \
ino=13 scontext=u:r:vendor_init:s0 tcontext=u:object_r:unlabeled:s0 tclass=file
avc: denied { relabelfrom } for comm="init" name="sensors_settings" \
dev="mmcblk0p44" ino=13 scontext=u:r:vendor_init:s0 \
tcontext=u:object_r:unlabeled:s0 tclass=file
> [WIP] vendor_init: Fix /mnt/vendor/persist/ labels

- vendor/tad.te
08-27 15:58:31.154   656   656 I tftp_server: type=1400 audit(0.0:3): avc: denied { setattr } for name=modem dev=sda66 ino=2621469 scontext=u:r:tad:s0 tcontext=u:object_r:vendor_data_file:s0 tclass=dir permissive=1
> avoid tad denials

- vendor/file.te
- vendor/file_contexts
- vendor/system_app.te
For https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/49.
> [3/4] Allow ExtendedSettings (system_app) to read sysfs_glove_mode.

- BUGSs.md
- vendor/netmgrd.te
Since device-sony-common@a321b9 sepolicy is compiled with
`PRODUCT_SEPOLICY_SPLIT_OVERRIDE := true`
That means the content of `not_full_treble()` macros is ignored.
> netutils: Remove unused legacy access

- vendor/vendor_init.te
- vendor/vendor_toolbox.te
(Accompanies https://github.com/sonyxperiadev/device-sony-common/pull/613)
Certain commands from the vendor toybox located at `/vendor/bin/toybox_vendor` may be executed directly by our vendor init.
The exec for `toybox_vendor setfattr` was moved from the `vendor_init` to the `vendor_toolbox` context.
Since the exec statement for the `toybox_vendor setfattr` operation was moved into the `vendor_toolbox` context, `vendor_init` needs less permissions.
> [Q-COMPAT] Update toybox run context

- vendor/kernel.te
Diag and wlan debugging stuff is only needed in `userdebug` builds
`avc: denied { create } for comm="kworker/u8:2" scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=socket`
> Kernel sockets for user/-debug

- vendor/tad.te
- vendor/tee.te
On android Q, this is a requirement (though I cannot find where it changed, apart a `neverallowxperm` which doesn't change the situation).
Entering the device pincode will fail on startup (Mermaid) and Discovery fails to boot altogether without these.
There is no harm in adding these on Pie (in fact, pretty much all other ioctls are explicit already and no further denials show up).
> tad/tee: Specify which ioctls are called on blk_file

- BUGSs.md
- sepolicy.mk
- vendor/file.te
- vendor/file_contexts
- vendor/genfs_contexts
- vendor/keystore.te
- vendor/netmgrd.te
- vendor/thermalserviced.te
- vendor/usbd.te
This removes a couple temporary fixes that were necessary on Pie but can now be removed because Google fixed this upstream.
Please check a87ff28. Only one line needed to be removed to build the policy (separated into b1d56af), but these "coredomain patchups" do not seem necessary anymore (no denials, Loire works fine without the `keystore` rule). If anyone experiences problems/denials, we can always re-add them.
Also, take note of ac5c258: This removes `BOARD_SEPOLICY_VERS` which has a proper default (one that is similar to `$(PLATFORM_SDK_VERSION).0` but without the chance to have letters in it on preview sources).
You will see a `Warning: BOARD_SEPOLICY_VERS is not specified. Default to 0.0.` regardless! As explained in the commit, this is from external manifests that do not get the …
> [Android 10] Drop deprecated patches; remove superfluous versioning; bump HAl version.

- vendor/genfs_contexts
01-17 08:56:54.459     1     1 W init    : type=1400 audit(0.0:5): avc: denied { setattr } for name=trigger dev=sysfs ino=44654 scontext=u:r:init:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
01-17 08:56:54.460     1     1 W init    : type=1400 audit(0.0:6): avc: denied { setattr } for name=activate dev=sysfs ino=44663 scontext=u:r:init:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
01-17 08:56:54.460     1     1 W init    : type=1400 audit(0.0:7): avc: denied { setattr } for name=brightness dev=sysfs ino=44652 scontext=u:r:init:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
01-17 08:56:54.460     1     1 W init    : type=1400 audit(0.0:8): avc: denied { setattr } for name=duration dev=sysfs ino=44662 scontext=u:r:init:s0 tcontext=u:object_r:sysfs:s0 …
> sepolicy: add LDO vibrator sys path

- BUGSs.md
- vendor/file_contexts
- vendor/hal_camera_default.te
- vendor/hal_gnss_qti.te
- vendor/hal_imsrtp.te
- vendor/hal_sensors_default.te
- vendor/ims.te
- vendor/ioctl_defines
- vendor/ioctl_macros
- vendor/irsc_util.te
- vendor/mlog_qmi.te
- vendor/netmgrd.te
- vendor/pd_services.te
- vendor/per_mgr.te
- vendor/qmuxd.te
- vendor/qrtr.te
- vendor/rild.te
- vendor/rmt_storage.te
- vendor/sct.te
- vendor/sensors.te
- vendor/system_server.te
- vendor/ta_qmi.te
- vendor/te_macros
- vendor/wcnss_service.te
Add a macro that allows interaction with qipcrtr_socket files. This
macro provides legacy access to ipc-router sockets. When 4.14 is final
and sepolicy branches off for "legacy" 4.9 compatibility, the socket
allow and related allowxperm rules must be removed.
I am not too sure about the macro, since we already had to label every `allowxperm` with a `TODO`. Might as well leave the `allow xyz self:socket ...;` in place and remove the (now useless) macro.
Pinging @ix5, my partner-in-crime when it comes to sepolicy for an opinion.
> [DONOTMERGE] [LA.UM.7.1.r1] Convert to QRTR sockets

- vendor/hal_bluetooth_default.te
- vendor/rild.te
This rule magically disappeared from the previous commit (https://github.com/sonyxperiadev/device-sony-sepolicy/pull/538)
**Please** Do a quick compile test! I vaguely remember something generating a `neverallow`, perhaps that was this rule...
> FIXUP: rild: Allow qipcrtr socket access.

- vendor/hal_bluetooth_default.te
This HAL did not previously have the rules to access the ipc-router
socket, but turns out to be using qrtr on 4.14.
> FIXUP: bluetooth: Allow access to qipcrtr socket.

- vendor/genfs_contexts
- vendor/hal_vibrator_default.te
Denials:
```
avc: denied { open } for path="/sys/devices/platform/soc/soc:ldo_vibrator/leds/vibrator/trigger" \
dev="sysfs" ino=39952 scontext=u:r:init:s0 tcontext=u:object_r:sysfs:s0 tclass=file
avc: denied { read write } for comm="android.hardwar" name="activate" dev="sysfs" \
ino=39961 scontext=u:r:hal_vibrator_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file
```
Ah, my sweet enforcing state shall be restored swiftly on 10... 
(The vibrator HAL fails without this and craps out, stalling boot.)
> [Q-Compat] Label and access vibrator paths

- vendor/file.te
- vendor/genfs_contexts
- vendor/hal_health_default.te
- vendor/property.te
- vendor/property_contexts
- vendor/shell.te
- vendor/vold.te
Accompanies https://github.com/sonyxperiadev/device-sony-common/pull/628
Vold would have access to /sys/block/mmcblk0 because it can access all of u:r:sysfs:s0. But since we have labeled the mmc nodes differently, vold needs access to the new labels:
> [2/2] [WIP] health: Storage stats

- vendor/file.te
- vendor/genfs_contexts
- vendor/vendor_init.te
vendor init needs to write usb_f_mtp params to sysfs.
See https://github.com/sonyxperiadev/device-sony-tone/pull/184
https://github.com/sonyxperiadev/device-sony-loire/pull/253
See https://github.com/sonyxperiadev/bug_tracker/issues/432#issuecomment-517964636
> [VERIFYME] Label and access /sys/module/usb_f_mtp

- vendor/file_contexts
See https://github.com/sonyxperiadev/device-sony-tama/pull/66
> The new adsprpc driver opens one device for secure transactions and
> one for unsecured transactions.
> [VERIFYME] file_contexts: Label /dev/adsprpc-smd-secure

- vendor/file.te
- vendor/file_contexts
- vendor/genfs_contexts
- vendor/hal_camera_default.te
- vendor/hal_graphics_composer_default.te
- vendor/hal_power_default.te
- vendor/hwservice.te
- vendor/hwservice_contexts
- vendor/kernel.te
- vendor/qcrilam_app.te
- vendor/rild.te
- vendor/rmt_storage.te
- vendor/sensors.te
- vendor/sscrpcd.te
- vendor/tad.te
This is the first iteration of rules for the new HALs that come with kernel 4.14. So far no denials have been spotted during short normal use (apart rogue apps trying to read anything and everything in the system...).
@ix5 I need your opinion on the following. ~Please do not merge this until we have resolved these points.~ Discussed, ready to merge!
- Libs with multiple versions: Is `mapper@[0-9]+\.[0-9]+\.so` ok or do you prefer all the versions explicitly listed? (1.0, 1.1 and 3.0 in this case)
- The new CAF/QTI interfaces (for the graphics mapper and allocator) inherit from AOSP (`interface IQti* extends I*`) and are supposed to bolt right into the existing structure. I don't think it makes any sense to redefine entire domains and pretty much duplicate AOSP policy when we can give …
> [LA.UM.7.1.r1] Sepolicy for kernel 4.14 paths and new HALs

- vendor/hal_fingerprint_default.te
For https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/50
Now that we can get the sensor to detect swipe gestures, allow the HAL to send the "generated keycodes" to the system through uinput.
> [2/7] hal_fingerprint_default: Allow emitting events to uinput.

- vendor/qcrilam_app.te
For https://github.com/sonyxperiadev/QcRilAm/pull/4
QcRilAm has been converted to use only SDK APIs instead of private ones,
for building on devices with API level 28 and up.
The app now has to get the sim count through SubscriptionManager, which
internally uses the ISub interface.
This fixes the following denial:
denied  { find } for service=isub scontext=u:r:qcrilam_app:s0
tcontext=u:object_r:radio_service:s0 tclass=service_manager
> [2/2] QcRilAm: Grant access to isub (radio_service) for sim information.

- vendor/hal_bootctl_default.te
- vendor/hal_gnss_qti.te
- vendor/hal_graphics_composer_default.te
- vendor/hal_wifi_default.te
- vendor/irsc_util.te
- vendor/property_contexts
- vendor/rild.te
- vendor/te_macros
Follows on the changes made in https://github.com/sonyxperiadev/device-sony-sepolicy/pull/550
See the commits and their respective descriptions/changes for more details.
> [LA.UM.7.1.r1] Second sepolicy dump for 4.14

- vendor/hal_wifi_default.te
11-22 12:44:53.700   691   691 W wifi@1.0-servic: type=1400 audit(0.0:81): avc: denied { create } for name=driver_prints_rbXURHagokgH scontext=u:r:hal_wifi_default:s0 tcontext=u:object_r:tombstone_wifi_data_file:s0 tclass=file permissive=0
> sepolicy: avoid wifi denials

- vendor/file_contexts
- vendor/qcrild.te
For @kholk ;)
---
QCRILD is a Qualcomm Radio Interface Layer (RIL)
implementation, added in Kernel 4.14 blobs v4 for recent
devices.
This is the initial policy, to be expanded.
Test: Kagura - `make selinux_policy` -> OK
> [WIP] Add and label qcrild service

- vendor/dpmqmimgr.te
- vendor/hal_bluetooth_default.te
- vendor/hal_gnss_qti.te
- vendor/hal_graphics_composer_default.te
- vendor/hal_imsrtp.te
- vendor/hal_sensors_default.te
- vendor/hwservice.te
- vendor/hwservice_contexts
- vendor/ims.te
- vendor/netmgrd.te
- vendor/netutils_wrapper.te
- vendor/sensors.te
- vendor/sscrpcd.te
- vendor/te_macros
This cleans up access to diag_device and makes rules consistent across all services using it. Let me know if explicit file/dir permissions without **seemingly unrequested** ioctl/lock (perhaps map too) is desired.
The initial policy for `dpmQmiMgr` is included. `dpmd` will follow when it is more stable.
> [WIP] dpmQmiMgr and Kumano v4 policy

- vendor/file_contexts
- vendor/property_contexts
- vendor/qcrild.te
- vendor/rild.te
Qcrild is the successor of rild. It:
- Needs roughly the same permissions as rild;
- Cannot add the same services as the rild domain;
- `rild' is an AOSP domain with sensible default rules that do not need
to be duplicated in SODP policy.
Label it as rild for these reasons.
---
No other rild related denials are observed on Griffin DSDS (with a single SIM inserted). Cellular and mobile data work correctly.
> qcrild: Label as rild

- BUGSs.md
- vendor/rild.te
The qcrild labels and domain were reverted because this is not
compatible with the specific `rild` domain exposed by AOSP, and
add_hwservice explicitly disallows multiple domains from hosting the
same service (which would be the case with a concurrent `rild` and
`qcrild` domain). See previous commits for more details.
However, ODM V4 has already been released with this stray qcrild_exec
label. Re-add it and allow the executable to transition into the rild
domain.
> TEMPORARY: rild: Transition from wrong qcrild_exec label to rild domain

- vendor/hwservice.te
- vendor/hwservice_contexts
- vendor/rild.te
The new qcrild wants to host the IIWlan interface.
Solves the following denial:
denied  { add } for interface=vendor.qti.hardware.data.iwlan::IIWlan
scontext=u:r:rild:s0 tcontext=u:object_r:default_android_hwservice:s0
tclass=hwservice_manager
> [SEPOLICY] rild: Label and start data.iwlan::IIWlan service.

- vendor/file_contexts
Kumano uses a new driver that names its node /dev/pn553. To prevent
clashes in the future, label anything in the pn5 range.
> [SEPOLICY] file_contexts: Update NFC node property to include all of pn5[0-9]+

- vendor/file_contexts
The device is named "pn54x" for legacy devices, which wasn't being caught by the number-only regex.
Obligatory proof:
`avc: denied { read write } for comm="nfc@1.2-service" name="pn54x" dev="tmpfs" ino=13934 scontext=u:r:hal_nfc_default:s0 tcontext=u:object_r:device:s0 tclass=chr_file`
> file_context: Fix NFC node once again

- vendor/seapp_contexts
https://github.com/sonyxperiadev/QcRilAm/pull/7
QcRilAm has been updated to run as normal user rather than sharing
everything with the system user. This means that user=system doesn't
match, the app receives the wrong context and everything falls apart.
Update it to _app to match it running as uX_aYYY like any other app.
Also remove the comment which doesn't seem applicable anymore. There are
multiple matching rules involved in the process and priv-app is not a
requirement:
https://github.com/sonyxperiadev/QcRilAm/commit/4a4608a8982ffc5d2612c9da4e20acb635e10061#diff-3ae6be565f1e33e90e0b11f768de1f6c
QcRilAm is not a priv-app anymore for some time. If matching against
such strict matching is really required, use isPrivApp=true/false.
> seapp_contexts: qcrilam runs as normal app user now

- vendor/charger.te
- vendor/file.te
- vendor/hal_health_default.te
These lines have "recently" been added to AOSP rules, no need to redeclare them anymore :smile: 
(Note that this policy was written well before those commits in AOSP were even made)
Requires the following PRs to be merged first:
https://github.com/sonyxperiadev/device-sony-nile/pull/109
https://github.com/sonyxperiadev/device-sony-ganges/pull/30
https://github.com/sonyxperiadev/device-sony-seine/pull/1
Tested on Mermaid DSDS, no new denials show up.
> [SEPOLICY] Remove AOSP-duplicates for charger and hal_health_default

- README.md
- vendor/adpl.te
- vendor/device.te
- vendor/dpmd.te
- vendor/dpmqmimgr.te
- vendor/file.te
- vendor/file_contexts
- vendor/hal_gnss_qti.te
- vendor/qti.te
A rather small patchset providing the initial policy for new services: dpm, (data)adpl and (data)qti. Following up with small fixes to `dpmQmiMgr` and `GNSS` 2.0.
Finally a small reordering in the README:
> Specifying what the domain exposes to the rest of the system before listing what it "needs" from other services seems like a more logical approach.
dpm wants a bit too much:
```
denied { dac_override } for comm="dpmd" capability=1 scontext=u:r:dpmd:s0 tcontext=u:r:dpmd:s0 tclass=capability
denied { setuid } for comm="dpmd" capability=7 scontext=u:r:dpmd:s0 tcontext=u:r:dpmd:s0 tclass=capability
```
The service _seems_ to run fine without, but more investigation is needed (these generally mean borked `open()` flags of readonly files etc).
Please review thoroughly before merging!
> [SEPOLICY] Oem-v7 part1: dpm, adpl, qti, gnss

- BUGSs.md
- vendor/file.te
- vendor/hal_fingerprint_default.te
- vendor/ueventd.te
This is needed because 64bit A/B GSIs use these labels in /system_root because of ...some legacy qcom reasons.
See https://android.googlesource.com/platform/build/+/refs/tags/android-9.0.0_r47/target/board/generic_arm64_ab/sepolicy/file_contexts
(We have our own label `u:object_r:rootfs:s0` for `/firmware` already, but with system-as-root, the `/firmware` symlink resides inside the GSI and we thus cannot change the label.)
Denials:
```
QSEECOMAPI: Error::Cannot open the file \
/firmware/image/egisap32.mdt errno = 13
QSEECOMAPI: Error::Loading image failed with ret = -1
android.hardwar: type=1400 audit(0.0:95): avc: denied { search } \
for name="firmware" dev="dm-0" ino=4347 \
scontext=u:r:hal_fingerprint_default:s0 \
tcontext=u:object_r:unlabeled:s0 tclass=dir
```
> firmware_file GSI compat

- vendor/file_contexts
- vendor/hal_fingerprint_default.te
- vendor/ueventd.te
Drop `rootfs` labeling for `/firmware`, `/dsp` and `/bt_firmware`, which are all gone now.
Also partially revert the previous commit that grants access to an alternate `/firmware` label as well, which was intended to be superseded by migrating everything to `/vendor/firmware_mnt` entirely. But there's a case to be made for these changes, as `/firmware` still exists on most GSIs and is scanned first before our `/vendor/firmware_mnt/image/` is checked. This results in misleading permission denials.
@ix5 I started indifferent, but am at this point biased towards making it a `dontaudit` entirely. My reasoning to hide it:
- We all build and test our devices without this `/firmware` link now. If something breaks we will notice;
- If something can't find its firmware the denial will not be the …
> [SEPOLICY] Remove labeling contexts for removed rootfs symlinks

- vendor/hal_miscta_default.te
- vendor/hal_modemsw_default.te
- vendor/hwservice.te
- vendor/hwservice_contexts
- vendor/init.te
- vendor/modemconfig_app.te
- vendor/modemsw.te
- vendor/property.te
- vendor/property_contexts
- vendor/seapp_contexts
Provide a baseline policy for modemflasher, including broken vendor props and all.
Needs some thorough review and a test for completeness on multiple platforms.
> [SEPOLICY] Declare services and apps for modem switcher

- vendor/file.te
- vendor/file_contexts
- vendor/tee.te
A new configuration for the GP FS listener [1] MAY use/move some files
in /data/vendor/tzstorage (to prevent non-vendor files ending up in
system folders such as /data/{system,misc}. Grant full readwrite access
to these folders by qseecomd.
qseecomd: avc: denied { read } for name="tzstorage" dev="sda73" scontext=u:r:tee:s0 tcontext=u:object_r:vendor_data_file:s0 tclass=dir
[1]: https://github.com/sonyxperiadev/device-sony-common/commit/547687c20fb2d5d2c763d4fd7c929302da269973
> [SEPOLICY] tee: Label and grant access to new /data/vendor/tzstorage folder

- vendor/adsprpcd.te
- vendor/file_contexts
Label `gralloc` and `vulkan` HW modules for Seine/PDX201 (SM6125) and update `adsprcpd` with rw access to /mnt/vendor/persist/sensors.
> [SEPOLICY] adsprpcd updates and hw module labels for Seine

- vendor/hal_audio_default.te
Update policy to allow connecting to IMisctaGlobal over binder, which
we recently switched to in [1]:
avc:  denied  { find } for
interface=vendor.somc.hardware.miscta::IMisctaGlobal
sid=u:r:hal_audio_default:s0 pid=627
scontext=u:r:hal_audio_default:s0
tcontext=u:object_r:vnd_somc_miscta_hwservice:s0
tclass=hwservice_manager
avc: denied { call } for scontext=u:r:hal_audio_default:s0
tcontext=u:r:hal_miscta_default:s0 tclass=binder
[1]: https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/pull/4
> [SEPOLICY] audio: Allow access to IMisctaGlobal

- vendor/device.te
- vendor/file_contexts
- vendor/hvdcp_opti.te
- vendor/property.te
- vendor/property_contexts
Conver audit2allow rules to something sensible, turn generic labels (on the properties and `/dev/qg{,_battery}`) into specific ones, and allow the missing kmsg write.
Note that I couldn't see `allow hvdcp_opti init:unix_stream_socket connectto;` being used anywhere.
> [SEPOLICY] Update the hvdcp policy

- vendor/fastbootd.te
These block devices are not allowed to be flashed in AOSP policy but can be flashed from fastbootd.
This change requires the file nodes for them to be labeled properly in device repositories.
See seine: https://github.com/sonyxperiadev/device-sony-seine/pull/18
> [SEPOLICY] fastbootd: Allow flashing of recovery, dtbo and vbmeta block devices

- vendor/file.te
- vendor/system_app.te
**DO NOT MERGE:** The `sysfs_mac_address` type declaration would throw a build error if merged on current Q master.
Minor adaptation to current master/R.
`sysfs_mac_address` was removed, but we are still using it
`perfprofd` is gone entirely.
> [DONOTMERGE] [R] Minor: sysfs_mac_address, perfprofd removal

- vendor/hal_audio_default.te
Allow the Audio HAL to read thermal information. Solves:
denied { search } for name="thermal" dev="sysfs" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir
denied { read } for name="thermal" dev="sysfs" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir
denied { read } for name="class" dev="sysfs" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:sysfs:s0 tclass=dir
msm8974_platform: Unable to open /sys/class/thermal
> [SEPOLICY] [Q/R] hal_audio_default: Allow reading thermal status

- vendor/modemconfig_app.te
- vendor/qcrilam_app.te
app_api_service is now broadly in Android R to encapsulate all normal
system services an app should have access to. Issues were initially
noticed when these two apps repeatedly spew the following denials every
half second:
denied  { find } for name=tethering scontext=u:r:modemconfig_app:s0 tcontext=u:object_r:tethering_service:s0 tclass=service_manager
denied  { find } for name=tethering scontext=u:r:qcrilam_app:s0 tcontext=u:object_r:tethering_service:s0 tclass=service_manager
It is clear that all other app types (priv_app and such) have access to
these services through app_api_service; grant our apps access to it too.
> [SEPOLICY] [R] app: Migrate service rules to app_api_service

- vendor/hal_miscta_default.te
On Android R restrictions on fd sharing seem to be more strict,
resulting in the following error observed on Seine:
E vendor.somc.hardware.miscta@1.0-service: MisctaGlobal::misctaReadUnit: hidl memory mapping failed!
E audio_hw_sony_cirrus_playback: get_ta_array: Cannot read TA unit 4702 of size 4: error 1
I audio_hw_sony_cirrus_playback: get_ta_array: Read TA unit 4702 (size=4) values: 0x0 0x0 0x0 0x0
D msm8974_platform: platform_get_snd_device_backend_interface: hw_interface set for device HDMI
W avc: denied { use } for path="/dev/ashmeme729d33a-ee97-4fa2-b8c3-f6200874e6ef" scontext=u:r:hal_miscta_default:s0 tcontext=u:r:hal_allocator_default:s0 tclass=fd
Instead of granting this permission directly or through the missing
binder_call macro, make hal_miscta_default part of the …
> [SEPOLICY] [Q/R] hal_miscta_default: Add to hal_allocator client domain

- vendor/hwservice.te
- vendor/hwservice_contexts
- vendor/ims.te
The first ODM release for Android 11 contains this new service:
E SELinux : avc:  denied  { find } for interface=vendor.qti.ims.factory::IImsFactory sid=u:r:ims:s0 scontext=u:r:ims:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager
E HidlServiceManagement: Service vendor.qti.ims.factory@1.0::IImsFactory/default must be in VINTF manifest in order to register/get.
F imsrcsd : ImsRcsBaseImpl.cpp:101] Check failed: ((ImsFactory*) m_pImsFactory)->registerAsService() == android::NO_ERROR (((ImsFactory*) m_pImsFactory)->registerAsService()=-2147483648, android::NO_ERROR=0) Failed to register ImsFactory HAL
> [SEPOLICY] [R/ODM] Add IImsFactory interface, hosted by the ims domain

- BUGSs.md
- vendor/cnd.te
- vendor/hal_telephony.te
- vendor/qcrilam_app.te
- vendor/rild.te
On seine we're observing the following:
avc:  denied  { find } for interface=vendor.qti.hardware.data.iwlan::IIWlan sid=u:r:radio:s0 scontext=u:r:radio:s0 tcontext=u:object_r:vnd_data_iwlan_hwservice:s0 tclass=hwservice_manager
avc:  denied  { find } for interface=vendor.qti.data.factory::IFactory sid=u:r:radio:s0 scontext=u:r:radio:s0 tcontext=u:object_r:vnd_data_factory_hwservice:s0 tclass=hwservice_manager
While we could explicitly allow `radio` to find these services, and consequently grant binder access back and forth between radio and the hosting domains (`rild` and `cnd` respectively), AOSP policy already has special macros and attributes in place to confine a triple of these parts:
- Client(s) for a specific service or group of services (`hal_client_domain`);
- Server(s) who are …
> [SEPOLICY] [RFC] Move all radio-related hwservices into the hal_telephony "binder domain"

- vendor/file_contexts
LA.UM.9.xx display HALs now provide a composer executable directly instead of going through `android.hardware.graphics.composer@x.y-service` and a libhardware module.
> [SEPOLICY] [R] file_contexts: Label QTI display.composer-service

- vendor/atfwd_daemon.te
- vendor/file_contexts
- vendor/mdm_helper.te
These are just the labels so that the binaries are properly labeled next time `/odm` is built; actual policy comes later.
See also https://github.com/sonyxperiadev/device-sony-common/pull/811
> [SEPOLICY] [R] Add labels for new mdm_helper and ATFWD-daemon

- vendor/device.te
- vendor/hal_bootctl_default.te
- vendor/init.te
Allow init to relabel "custom" block devices, and remove `gpt_block_device` which serves the same purpose as `root_block_device` from AOSP.
> [SEPOLICY] [Q/R] Init relabelto for more block devices, remove gpt_block_device

- vendor/file_contexts
- vendor/hal_graphics_composer_default.te
- vendor/hwservice_contexts
- vendor/sscrpcd.te
This is an initial set of rules to accept the new 9.12 graphics stack with different binaries and more HIDL/HAL revisions. One other patch for wakelocks in sscrpcd, all the new binaries (atfwd, mdm etc) will be done at a later date. This at least allows edo to boot in enforcing.
> [sepolicy] [R] Initial (graphics) labels and rules for edo support

- vendor/hal_graphics_composer_default.te
Newer display composers (like those on 8.1 and 9.12 tags) support setting brightness directly instead of going through the lights HAL. On 8.1 this was so horribly broken that we ended up disabling it [1], but on 9.12 it is implicitly working just fine. For this the HAL now requires write access to led files.
Note that it might be saner to define a new `sysfs_backlight` for this; leds seem to be a remnant from ancient kernels having the backlight under `class/leds`, but alas - that requires updating _all_ platforms.
[1]: https://github.com/sonyxperiadev/hardware-qcom-display/pull/32
---
@jerpelea please do the usual rebase after merging this :grimacing:
> [sepolicy] [Q/R] hal_graphics_composer_default: Grant write access to "leds"

- vendor/file_contexts
We are upgrading to a new version again (2.1 this time), and repeatedly bumping these in policy is tedious. We should probably give the entire set of labels a good scrutineering and replace all numbers with `[0-9]+` to match the nature of constantly changing revisions.
> [sepolicy] [R/master] file_contexts: Label all gnss service binary revisions

- vendor/qtidataservices_app.te
- vendor/seapp_contexts
Without this commit I had no service with enforcing before, for some reason.
Turning airplane mode on/off would also spam the denial.
Simply doing
```
allow platform_app vnd_data_iwlan_hwservice:hwservice_manager { find };
```
would yield a neverallow.
Tested on kumano/bahamut.
> [R] Split qtidataservices_app from platform_app

- vendor/file_contexts
Add android.hardware.usb@1.2-service-qti HAL for devices
running on 4.19 kernel.
This version of the USB HAL is not intended to be used
on targets with kernels older than 4.19 (since it relies on
Type-C Class to be enabled).
> [master] Add support for QTI USB HAL

- sepolicy.mk
In Android S (12) the BOARD_PLAT_`*`_SEPOLICY_DIR variables
have been renamed to SYSTEM_EXT_`*`_SEPOLICY_DIRS.
See for reference: https://android-review.googlesource.com/q/topic:board-system-ext-sepolicy
> [S] sepolicy.mk: Follow rename change from upstream

- vendor/device.te
- vendor/mdm_helper.te
These two patches should address all the remaining sepolicy warnings around `mdm_helper`.
> [R/S] mdm_helper: Allow executing "kickstart" and grant read-access to efs sync partitions

- vendor/genfs_contexts
- vendor/hal_bluetooth_default.te
- vendor/hal_memtrack_default.te
- vendor/hal_power_default.te
- vendor/hal_wifi_default.te
- vendor/kernel.te
- vendor/per_mgr.te
- vendor/rmt_storage.te
debugfs is not cool anymore, aosp says it's a strict neverallow :(
> treewide: remove debugfs entries

- vendor/bootanim.te
- vendor/file.te
- vendor/file_contexts
- vendor/hal_graphics_allocator_default.te
- vendor/hal_graphics_composer_default.te
- vendor/platform_app.te
- vendor/priv_app.te
- vendor/surfaceflinger.te
- vendor/system_app.te
- vendor/system_server.te
Add  a new file context label for gpu_model sysfs entry. allowed read access to that entry.
Addressing the following denials:
type=1400 audit(0.0:4726): avc: denied { read } for name="gpu_model" dev="sysfs" ino=58119 scontext=u:r:system_server:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
type=1400 audit(0.0:32):   avc: denied { read } for name="gpu_model" dev="sysfs" ino=59584 scontext=u:r:hal_graphics_composer_default:s0 tcontext=u:object_r:sysfs_kgsl_gpu_model:s0 tclass=file permissive=1
type=1400 audit(0.0:48):   avc: denied { read } for name="gpu_model" dev="sysfs" ino=59584 scontext=u:r:hal_graphics_allocator_default:s0 tcontext=u:object_r:sysfs_kgsl_gpu_model:s0 tclass=file permissive=1
type=1400 audit(0.0:45):   avc: denied { read } for name="gpu_model" dev="sysfs" …
> [t-mr1] vendor: Define new policy rule to read gpu model

- vendor/device.te
Ref Repo : https://android.googlesource.com/platform/system/sepolicy/+/refs/tags/android-14.0.0_r30/public/device.te#99
Ref Commit : https://android.googlesource.com/platform/system/sepolicy/+/5d0ef8448f165bdfe59b01d822798a3276c6ca09
Error : device/sony/sepolicy/vendor/device.te:30:ERROR 'Duplicate declaration of type' at token ';'
on line 90868:
type dtbo_block_device, dev_type;
> Remove dtbo_block_device which is defined in AOSP since QPR2

- vendor/file_contexts
Closes https://github.com/sonyxperiadev/device-sony-sepolicy/pull/611, CC @ShujathMohd
Since the migration to `health@2.1` in [#918] we're using the builtin passthrough service that loads our custom implementation from an `impl` library.  Android's builtin vendor sepolicy already labels this binary with `hal_health_default_exec`, and the `2.0-service.sony` file is no longer provided and should be removed.
[#918]: https://github.com/sonyxperiadev/device-sony-common/pull/918
> [T/U] file_contexts: Drop executable label for custom health HAL

- vendor/file_contexts
- vendor/hwservice_contexts
- vendor/service_contexts
New QTI camera provider is used by k5.15+ devices.
Add vendor.qti.camera.provider-service_64 to file_contexts.
Also add permissions for AON and PostProc camera services.
> [t-mr1] vendor: Add SEpolicy for AIDL QTI camera provider

- vendor/file_contexts
We are going to switch GNSS to AIDL implementation.
Label android.hardware.gnss-aidl-service-qti AIDL service.
> [u-mr1] file_contexts: Switch to GNSS AIDL HAL

- vendor/file_contexts
We are going to switch vibrator to AIDL implementation.
Label vendor.qti.hardware.vibrator.service AIDL service.
The QTI Vibrator AIDL HAL can handle all hardware from
Seine to Yodo.
> [u-mr1] file_contexts: Switch to Vibrator AIDL HAL

- vendor/file_contexts
We are going to switch NXP NFC HAL to AIDL implementation.
Label android.hardware.nfc-service.nxp AIDL service.
> [u-mr1] file_contexts: Add NXP NFC AIDL HAL
