sonyxperiadev/device-sony-sepolicy

init.te

Fix init denials

---

touchfusion.te

Fix touchfusion denials

---

kernel.te

Change-Id: I52c7391c721f9d2b718db6e44c83857ea1a50714

sony: sepolicy: Fix touchfusion denials for TWRP

---

file_contexts
peripheral_manager.te

Defining the block devices stops most of the denials
more device specific denails will come later
also fix some minor typos in related definitions

suzu: fundemental definitions

---

surfaceflinger.te
system_server.te

sepolicy: Avoid Binder denials

---

file_contexts

Bug: 26219114
Change-Id: I0d0f1ac10b347b68095d9636c82293648e5b70a1

Label /sys/class/power_supply/battery/capacity.

---

file_contexts

following: 838fb9b0ec258b5f6df585e88867b6cd45df12e2

Label /sys/class/power_supply/battery/capacity kitakami

---

device.te
file_contexts
system_app.te

sepolicy: add SELInux for FMRadio

---

file_contexts

[master] sony: sepolicy: Label zram block device

---

file_contexts
qseecomd.te

FPC permissions for loire

---

file_contexts
qseecomd.te

[master] FPC permissions for loire

---

file_contexts

[m-mr1] Fix FPC denials for Kitakami and Loire

---

addrsetup.te
irsc_util.te
mlog_qmi.te
mm-qcamerad.te
msm_irqbalanced.te
netmgrd.te
pad_controller.te
peripheral_manager.te
qmuxd.te
rmt_storage.te
sct.te
sensors.te
ta_qmi.te
tad.te
tfa_amp.te
thermanager.te
timekeep.te
touchfusion.te
wcnss_service.te

Bug: 25433265
Change-Id: I9563b9a4eb26856db021622f8217e4e3ab20f4cd

Grant all processes the domain_deprecated attribute

---

uim.te

Change-Id: I25ffe417f85febfe3c7ad69750fcf33506fb9d55

sony: sepolicy: Address uim service denials

---

uim.te

sepolicy: avoid uim denials

---

keystore.te

sepolicy: avoid keystore denials

---

mm-qcamerad.te

sepolicy: avoid camera denials

---

nfc.te

01-08 12:52:25.901  5416  5416 I ndroid.nfc:beam: type=1400 audit(0.0:8): avc: denied { search } for name=0 dev=mmcblk0p25 ino=757395 scontext=u:r:nfc:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
01-08 12:52:25.901  5416  5416 I ndroid.nfc:beam: type=1400 audit(0.0:9): avc: denied { write } for name=0 dev=mmcblk0p25 ino=757395 scontext=u:r:nfc:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
01-08 12:52:25.901  5416  5416 I ndroid.nfc:beam: type=1400 audit(0.0:10): avc: denied { add_name } for name=beam scontext=u:r:nfc:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=1
01-08 12:52:25.901  5416  5416 I ndroid.nfc:beam: type=1400 audit(0.0:11): avc: denied { create } for name=beam scontext=u:r:nfc:s0 …

sepolicy: avoid nfc denials

---

untrusted_app.te

sepolicy: fix build android-7.0

---

file_contexts

this branch was made to work with kernel 3.10

7.1 legacy

---

file_contexts

Sort in alphabetical order while here

sepolicy: add rild2 and rild-debug2 socket devices

---

file_contexts

This reverts commit bc0aceae01306b7a0035239572b0efdd3c10172d.

Revert "sepolicy: loire: fix macaddr path"

---

bluetooth.te

fix c5d7239f75e1721532d4e4ecec854c3d54adeb57

sepolicy: fix bt ioctl denial

---

audioserver.te
cameraserver.te
file_contexts
kernel.te
mm-qcamerad.te
priv_app.te
rild.te
touchfusion.te
untrusted_app.te

Change-Id: Id3cf10080b7fb888ca5b25f0c91911dcc37f0a93

[n-mr1] sony: sepolicy: Unify 3.10 and 3.18 requirements

---

file_contexts

on unify 3.18 kernel commit we miss it

sepolicy: fix tone blockdevice

---

vold.te

06-03 20:00:12.554   477   477 W vold    : type=1400 audit(0.0:7): avc: denied { read } for name=fd dev=proc ino=10178 scontext=u:r:vold:s0 tcontext=u:r:logd:s0 tclass=dir permissive=0
06-03 20:00:12.554   477   477 W vold    : type=1400 audit(0.0:8): avc: denied { getattr } for path=/proc/452/cwd dev=proc ino=50558 scontext=u:r:vold:s0 tcontext=u:r:logd:s0 tclass=lnk_file permissive=0
06-03 20:00:12.554   477   477 W vold    : type=1400 audit(0.0:9): avc: denied { getattr } for path=/proc/452/root dev=proc ino=50559 scontext=u:r:vold:s0 tcontext=u:r:logd:s0 tclass=lnk_file permissive=0
06-03 20:00:12.554   477   477 W vold    : type=1400 audit(0.0:10): avc: denied { getattr } for path=/proc/452/exe dev=proc ino=10187 scontext=u:r:vold:s0 tcontext=u:r:logd:s0 tclass=lnk_file permissive=0 …

sepolicy: avoid vold denials

---

vold.te

This fixes Encryption on (at least) tone devices

sepolicy: Allow vold to read the tee_prop

---

cameraserver.te
system_server.te

06-27 00:46:30.009   538   538 W cameraserver: type=1400 audit(0.0:5): avc: denied { read } for name=name dev=sysfs ino=36820 scontext=u:r:cameraserver:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
06-27 00:48:53.146  1071  1071 W PackageManager: type=1400 audit(0.0:15): avc: denied { getattr } for path=/data/media dev=mmcblk0p54 ino=791521 scontext=u:r:system_server:s0 tcontext=u:object_r:media_rw_data_file:s0 tclass=dir permissive=0
06-27 01:05:21.899   536   536 W cameraserver: type=1400 audit(0.0:5): avc: denied { open } for path="/sys/devices/soc/8c0000.qcom,msm-cam/video4linux/video0/name" dev="sysfs" ino=36820 scontext=u:r:cameraserver:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
06-27 01:05:21.899   536   536 W cameraserver: type=1400 audit(0.0:6): avc: …

sepolicy: fix 4.4 tone denials

---

audioserver.te
file.te
file_contexts
mediacodec.te
mediaserver.te
netmgrd.te
priv_app.te
rild.te
system_server.te

Fixes:
* mediaserver
* priv_app
Implementation:
* netmgrd
* powerhal

[master] Address selinux denials

---

cameraserver.te

06-30 15:20:59.529   885   885 W Binder:540_1: type=1400 audit(0.0:7): avc: denied { search } for name=powerhal dev=mmcblk0p54 ino=97967 scontext=u:r:cameraserver:s0 tcontext=u:object_r:powerhal_data_file:s0 tclass=dir permissive=0
06-30 15:20:59.689   885   885 W Binder:540_1: type=1400 audit(0.0:8): avc: denied { search } for name=powerhal dev=mmcblk0p54 ino=97967 scontext=u:r:cameraserver:s0 tcontext=u:object_r:powerhal_data_file:s0 tclass=dir permissive=0
06-30 15:20:59.729   540   540 W cameraserver: type=1400 audit(0.0:9): avc: denied { search } for name=powerhal dev=mmcblk0p54 ino=97967 scontext=u:r:cameraserver:s0 tcontext=u:object_r:powerhal_data_file:s0 tclass=dir permissive=0
06-30 15:20:59.859   885   885 W Binder:540_1: type=1400 audit(0.0:10): avc: denied { search } for …

sepolicy: fix powerhal denials

---

priv_app.te

06-13 23:23:24.587 20157 20157 W MtpServer: type=1400 audit(0.0:82): avc: denied { rename } for name=4E756F76612063617274656C6C61 dev=mmcblk1p1 ino=270 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vfat:s0 tclass=dir permissive=0
06-27 10:14:50.259  1992  1992 W MediaScannerSer: type=1400 audit(0.0:5): avc: denied { setattr } for name=.nomedia dev=mmcblk1p1 ino=203 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vfat:s0 tclass=file permissive=0
06-27 10:36:06.275  2935  2935 W MtpServer: type=1400 audit(0.0:6): avc: denied { add_name } for name=4E756F76612063617274656C6C61 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vfat:s0 tclass=dir permissive=0
06-27 10:43:29.033  3543  3543 W MtpServer: type=1400 audit(0.0:7): avc: denied { remove_name } for …

sepolicy: cleanup same entries

---

adsprpcd.te
app.te
file.te
file_contexts
init.te
mediacodec.te
mediaserver.te

It is required for acdb.
Change-Id: I3a22ad048ff9765f337bc1ca401d5610eab593cd

[master] sony: sepolicy: Implement adsprpcd rules

---

healthd.te

sepolicy: fix healthd denials

---

priv_app.te

07-11 00:27:01.851 22223 22223 W CTION_IDLE_MODE: type=1400 audit(0.0:92): avc: denied { getattr } for path=/data/data/com.android.providers.telephony dev=mmcblk0p54 ino=1175051 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:radio_data_file:s0 tclass=dir permissive=0
07-11 00:27:01.851 22223 22223 W CTION_IDLE_MODE: type=1400 audit(0.0:93): avc: denied { getattr } for path=/data/data/com.android.mms.service dev=mmcblk0p54 ino=1175078 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:radio_data_file:s0 tclass=dir permissive=0
07-11 00:27:01.851 22223 22223 W CTION_IDLE_MODE: type=1400 audit(0.0:94): avc: denied { getattr } for path=/data/data/android dev=mmcblk0p54 ino=1175111 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:system_app_data_file:s0 tclass=dir …

sepolicy: fix priv_app denials

---

untrusted_app.te

convert to macro style and remove double selinux def

sepolicy: cleanup untrusted_app perms

---

adsprpcd.te
app.te
file.te.orig
file_contexts
file_contexts.orig
init.te.orig
mediacodec.te
mediaserver.te
mediaserver.te.orig

Missing adsprpc rules in n-mr1!!!!

[SEPOLICY n-mr1] Add adsprpc rules

---

pd_mapper.te
tftp_server.te

Follow this commit 06653521ebaa7faeda7b97458bdf1bc0d8402c13
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>

Remove leftover domain_deprecated

---

bootanim.te
cameraserver.te
file.te
file_contexts
genfs_contexts
hal_audio_default.te
hal_fingerprint_default.te
hal_graphics_allocator_default.te
hal_graphics_composer_default.te
hal_memtrack_default.te
healthd.te
platform_app.te
service.te
surfaceflinger.te
system_server.te
vndservice_contexts

sepolicy: more o denials

---

file_contexts
nfc.te

sepolicy: fix nfc denials

---

hal_audio_default.te
hal_fingerprint_default.te
webview_zygote.te

sepolicy: o denials enforcing SELinux

---

hal_audio_default.te

04-29 04:36:16.579   669   669 W HwBinder:519_1: type=1400 audit(0.0:25): avc: denied { create } for name=Bluetooth_cal.acdbdelta scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:audio_data_file:s0 tclass=file permissive=0
04-29 04:36:16.579   669   669 W HwBinder:519_1: type=1400 audit(0.0:26): avc: denied { create } for name=General_cal.acdbdelta scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:audio_data_file:s0 tclass=file permissive=0
04-29 04:36:16.579   669   669 W HwBinder:519_1: type=1400 audit(0.0:27): avc: denied { create } for name=Global_cal.acdbdelta scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:audio_data_file:s0 tclass=file permissive=0
04-29 04:36:16.589   669   669 W HwBinder:519_1: type=1400 audit(0.0:28): avc: denied { create } for …

sepolicy: allow create acdb data files

---

cameraserver.te
hal_audio_default.te
hal_power_default.te
mediacodec.te

09-15 23:18:20.285   555   555 W power@1.0-servi: type=1400 audit(0.0:1571): avc: denied { getattr } for path=/data/misc/powerhal dev=mmcblk0p54 ino=97969 scontext=u:r:hal_power_default:s0 tcontext=u:object_r:powerhal_data_file:s0 tclass=dir permissive=0
09-15 23:18:20.286   555   555 W power@1.0-servi: type=1400 audit(0.0:1572): avc: denied { search } for name=powerhal dev=mmcblk0p54 ino=97969 scontext=u:r:hal_power_default:s0 tcontext=u:object_r:powerhal_data_file:s0 tclass=dir permissive=0
09-15 23:18:20.296   555   555 W power@1.0-servi: type=1400 audit(0.0:1574): avc: denied { write } for name=nr_run_thresholds dev=sysfs ino=44838 scontext=u:r:hal_power_default:s0 tcontext=u:object_r:sysfs_devices_system_cpu:s0 tclass=file permissive=0
09-15 23:18:20.297   555   555 W …

sepolicy: avoid powerHAL denials

---

hal_camera_default.te
vndservicemanager.te

05-08 04:09:43.687   552   552 W android.hardwar: type=1400 audit(0.0:23): avc: denied { read write } for name=vndbinder dev=tmpfs ino=11555 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:vndbinder_device:s0 tclass=chr_file permissive=0
09-16 22:04:23.213  1096  1096 W android.hardwar: type=1400 audit(0.0:421): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=9916 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
09-16 22:11:59.050   548   548 W provider@2.4-se: type=1400 audit(0.0:587): avc: denied { call } for scontext=u:r:hal_camera_default:s0 tcontext=u:r:vndservicemanager:s0 tclass=binder permissive=0
09-16 22:11:59.223   548   548 W provider@2.4-se: type=1400 audit(0.0:588): avc: denied { search } for …

sepolicy: avoid cam denials

---

file_contexts
hal_wifi_default.te

sepolicy: avoid binderized wifi denials

---

audioserver.te
cameraserver.te
file.te
file_contexts
hal_audio_default.te
hal_camera_default.te
hal_power_default.te
mediacodec.te
mediaserver.te
rild.te
system_server.te

needed after commit 499b64df1db61d815bbbda68179a376bd3d85e74 in sony/device/common

sepolicy: rewrite powerHAL SELinux

---

audioserver.te
hal_audio_default.te
hal_bluetooth_default.te
hal_camera_default.te
hal_drm_default.te
hal_fingerprint_default.te
hal_gatekeeper_default.te
hal_gnss_default.te
hal_graphics_allocator_default.te
hal_graphics_composer_default.te
hal_keymaster_default.te
hal_light_default.te
hal_memtrack_default.te
hal_nfc_default.te
hal_power_default.te
hal_sensors_default.te
hal_thermal_default.te
hal_vibrator_default.te
healthd.te
mediacodec.te
surfaceflinger.te
vold.te
zygote.te

09-26 20:59:06.779   485   485 W main    : type=1400 audit(0.0:115): avc: denied { search } for name=/ dev=mmcblk0p39 ino=2 scontext=u:r:zygote:s0 tcontext=u:object_r:oemfs:s0 tclass=dir permissive=0
09-26 20:59:07.429   515   515 W audio@2.0-servi: type=1400 audit(0.0:118): avc: denied { search } for name=/ dev=mmcblk0p39 ino=2 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:oemfs:s0 tclass=dir permissive=0
09-26 20:59:07.499   643   643 W audioserver: type=1400 audit(0.0:127): avc: denied { search } for name=/ dev=mmcblk0p39 ino=2 scontext=u:r:audioserver:s0 tcontext=u:object_r:oemfs:s0 tclass=dir permissive=0
09-26 20:59:12.889   655   655 W gnss@1.0-servic: type=1400 audit(0.0:146): avc: denied { search } for name=/ dev=mmcblk0p39 ino=2 scontext=u:r:hal_gnss_default:s0 …

sepolicy: avoid oemfs denials

---

file_contexts

sepolicy: move HALs to vendor

---

bluetooth.te
device.te
file_contexts
hal_bluetooth_default.te
init.te
start_hci_filter.te

based on https://source.codeaurora.org/quic/la/device/qcom/sepolicy/tree/?h=LA.UM.6.4.r1-03200-8x98.0

sepolicy: cleanup sepolicy according to CAF

---

file_contexts

sepolicy: avoid yoshino denials

---

priv_app.te
untrusted_app.te
untrusted_app_25.te

sepolicy: avoid various denials

---

hal_bluetooth_default.te
hal_gatekeeper_default.te
hal_keymaster_default.te
per_proxy.te
untrusted_app_all.te
wcnss_filter.te
wcnss_service.te

see individual commits for details

A range of sepolicy updates

---

init.te

[master] Add more configfs permissions for init

---

odmcheck.te

Messed up and forgot to git add the new file.
Build breaks without this!!
Note! I _think_ this is the latest version of the file, but this is from a backup since I managed to clean out the original file.

Added missing sepolicy file for odmcheck.

---

file_contexts
genfs_contexts
hal_bluetooth_default.te
mediacodec.te
mediaextractor.te
system_server.te
timekeep.te

[master] Fix mediacodec, mediaextractor, bluetooth, timkeep, hal_graphics_composer_default and system_server permissions

---

appdomain.te

Change-Id: Id92a934783d62b4c4c4230ecdb6da38ee8fad566

sony: sepolicy: Allow appdomain reading thermal sysfs

---

file.te
file_contexts
location.te
system_server.te

1. Define location domain
2. Add location new socket paths
3. Fix system_server denial
avc: denied { write } for name="socket_hal_xtra" dev="mmcblk0p54"
ino=516116 scontext=u:r:system_server:s0
tcontext=u:object_r:location_data_file:s0 tclass=sock_file permissive=0

[o-mr0] sony: sepolicy: Add location permissions

---

file.te
file_contexts
location.te
system_server.te

1. Define location domain
2. Add location new socket paths
3. Fix system_server denial
avc: denied { write } for name="socket_hal_xtra" dev="mmcblk0p54"
ino=516116 scontext=u:r:system_server:s0
tcontext=u:object_r:location_data_file:s0 tclass=sock_file permissive=0
Change-Id: If0a881161bb5d29f72d20308e9968a3851e32c1c

[master] sony: sepolicy: Add location permissions

---

hal_bluetooth_default.te
hal_gatekeeper_default.te
hal_keymaster_default.te

01-05 11:17:06.133  5032  5032 W HwBinder:619_2: type=1400 audit(0.0:214): avc: denied { search } for name=/ dev=sda39 ino=1 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:bt_firmware_file:s0 tclass=dir permissive=0
01-05 11:17:08.253  5087  5087 W HwBinder:619_2: type=1400 audit(0.0:215): avc: denied { search } for name=/ dev=sda33 ino=2 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:persist_file:s0 tclass=dir permissive=0
04-30 08:45:44.295   582   582 W android.hardwar: type=1400 audit(0.0:6): avc: denied { search } for name=/ dev=sda36 ino=1 scontext=u:r:hal_keymaster_default:s0 tcontext=u:object_r:firmware_file:s0 tclass=dir permissive=0
04-30 08:45:44.437   597   597 W android.hardwar: type=1400 audit(0.0:10): avc: denied { search } for name=/ dev=sda36 ino=1 …

sepolicy: avoid some denials

---

file_contexts

sepolicy: label 8996 for gralloc and vulkan libs

---

location.te
system_server.te

01-05 22:47:28.022   957   957 W xtra-daemon: type=1400 audit(0.0:26): avc: denied { search } for name=soc0 dev=sysfs ino=46040 scontext=u:r:location:s0 tcontext=u:object_r:sysfs_soc:s0 tclass=dir permissive=0
01-05 22:47:28.023   957   957 W xtra-daemon: type=1400 audit(0.0:28): avc: denied { search } for name=location dev=dm-0 ino=557059 scontext=u:r:location:s0 tcontext=u:object_r:location_data_file:s0 tclass=dir permissive=0
01-05 22:47:28.061   973   973 W cnss-daemon: type=1400 audit(0.0:32): avc: denied { search } for name=wifi dev=dm-0 ino=32784 scontext=u:r:wcnss_service:s0 tcontext=u:object_r:wifi_data_file:s0 tclass=dir permissive=0
01-05 23:06:33.057  1375  1375 W xtra-daemon: type=1400 audit(0.0:30): avc: denied { read } for name="hw_platform" dev="sysfs" ino=46068 …

sepolicy: avoid location denials

---

file.te
genfs_contexts
odmcheck.te
system_app.te
system_server.te

see luk1337 eplanation here https://github.com/sonyxperiadev/device-sony-sepolicy/pull/321

sepolicy: do not label /proc/version

---

file_contexts
rdclean.te

sepolicy: Make vendor script use vendor shell and vendor toybox

---

file_contexts
genfs_contexts
hal_bluetooth_default.te

sepolicy: improve file_contexts

---

ucommsvr.te

Update ucommsvr with cash changes

---

cashsvr.te

Change-Id: Idaf1e7495b3064a0da2a49762c7bc47d783d1630

sepolicy: Cleanup cashsvr rules to limit sysfs access of cashsvr

---

hal_graphics_composer_default.te
healthd.te
hwservice.te
hwservice_contexts
init.te
msm_irqbalanced.te
netd.te
proc_irq.te
zygote.te

sepolicy: avoid kernel 4.9 denials

---

vendor/file_contexts

following latest fstab updates in platforms

update /persist block label

---

vendor/attributes
vendor/file.te

sepolicy: changes for persist due to mount point changes

---

vendor/per_mgr.te
vendor/per_proxy.te
vendor/service.te
vendor/service_contexts
vendor/vndservice.te
vendor/vndservice_contexts

Reverts sonyxperiadev/device-sony-sepolicy#423

Revert "[WIP] PeripheralManager: Re-label as non-vendor type (temporarily), fix denials"

---

vendor/hal_imsrtp.te
vendor/ims.te
vendor/init.te
vendor/qmuxd.te

avoid ims & ril denials on qmuxd devices

---

vendor/file.te
vendor/file_contexts
vendor/genfs_contexts
vendor/hal_gnss_qti.te
vendor/hwservice_contexts
vendor/init.te
vendor/ipacm.te
vendor/netmgrd.te
vendor/pd_services.te
vendor/rdclean.te
vendor/sensors.te
vendor/sscrpcd.te
vendor/system_server.te
vendor/vendor_init.te
vendor/wcnss_service.te

Do not merge yet, some changes need to be discussed.

[2/3] Vendor updates for Pie: ipacm, (vendor_)init, file labeling, misc

---

vendor/hal_light_default.te

allow hal_lights read and write sysfs_leds paths

---

vendor/hal_wifi_hostapd_default.te

Denial:
avc: denied { search } for comm="hostapd" name="wifi" dev="mmcblk0p54" \
ino=294918 scontext=u:r:hal_wifi_hostapd_default:s0 \
tcontext=u:object_r:wifi_vendor_data_file:s0 tclass=dir

[WIP] hal_wifi_hostapd_default: search wifi data dir

---

private/crash_dump.te
private/webview_zygote.te

Since we missed the window for r30 and the status of the CLs in AOSP gerrit is unclear, these need to be included here in the meantime.
Relavant CLs:
- [crash_dump](https://r.android.com/867710)
- [webview_zygote](https://r.android.com/867711)

[WIP] Work around android bugs

---

vendor/hal_nfc_default.te

Denial:
avc: denied { add } for interface=vendor.nxp.nxpnfc::INxpNfc pid=1084 \
scontext=u:r:hal_nfc_default:s0 tcontext=u:object_r:nxpnfc_hwservice:s0 \
tclass=hwservice_manager

[WIP] hal_nfc_default: Add hwservice

---

BUGSs.md
vendor/ueventd.te

A good way to keep track of what needs to be done, and more visible than grepping for `TODO`s

Add bug map

---

vendor/hal_power_default.te
vendor/property.te
vendor/property_contexts

Label powerhal prop and allow access

Powerhal prop labels

---

vendor/priv_app.te

04-12 17:11:11.742  3306  3306 I Binder:3306_2: type=1400 audit(0.0:21): avc: denied { read } for name=address dev=sysfs ino=50814 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
04-12 17:11:11.742  3306  3306 I Binder:3306_2: type=1400 audit(0.0:22): avc: denied { open } for path=/sys/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/net/wlan0/address dev=sysfs ino=50814 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
04-12 17:11:11.742  3306  3306 I Binder:3306_2: type=1400 audit(0.0:23): avc: denied { getattr } for path=/sys/devices/platform/soc/600000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/net/wlan0/address dev=sysfs ino=50814 scontext=u:r:priv_app:s0:c512,c768 …

sepolicy: label brcmfmac mac_adress 2/2

---

vendor/file_contexts

sepolicy: label sm8150 gralloc and vulkan .so as sp-hal

---

vendor/device.te

add dtbo and vbmeta block device

sepolicy: updates

---

vendor/cnd.te
vendor/hal_wifi_supplicant_default.te

Allow cnd to create sockets and allow cnd to send data to sockets.

[SEPOLICY] Fix few denials for cnd

---

vendor/file_contexts

For https://github.com/sonyxperiadev/device-sony-common/pull/786

[SEPOLICY] [R] Update clearkey service to version 1.3

---

vendor/file_contexts
vendor/spu.te

@jerpelea plesae pull these in before building the next odm :wink:. These are just initial labels, actual policy follows later once we have definitive binaries.

[sepolicy] [R] Label authservice and spu odm binaries

---

BUGSs.md
private/dnsmasq.te
private/system_server.te
private/webview_zygote.te
sepolicy.mk
system_ext/private/init.te
system_ext/private/permissioncontroller_app.te
system_ext/private/radio.te
system_ext/private/shell.te
system_ext/public/dpmd.te
system_ext/public/file.te
vendor/dpmd.te
vendor/dpmqmimgr.te
vendor/file.te
vendor/file_contexts
vendor/ims.te

Plus general cleanup
**DNM** until we've verified the necessity of some calls.
@MarijnS95 get in here ;)

[DNM] [r-mr1] New BSP fixes

---

vendor/atfwd_daemon.te
vendor/device.te
vendor/file_contexts
vendor/mdm_helper.te

Head-start getting some services running.

[sepolicy] [R] Preliminary atfwd/mdm_helper modem policy
